// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: events.proto

package aws

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type AuditEvent struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Method               string   `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuditEvent) Reset()         { *m = AuditEvent{} }
func (m *AuditEvent) String() string { return proto.CompactTextString(m) }
func (*AuditEvent) ProtoMessage()    {}
func (*AuditEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{0}
}
func (m *AuditEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuditEvent.Unmarshal(m, b)
}
func (m *AuditEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuditEvent.Marshal(b, m, deterministic)
}
func (m *AuditEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuditEvent.Merge(m, src)
}
func (m *AuditEvent) XXX_Size() int {
	return xxx_messageInfo_AuditEvent.Size(m)
}
func (m *AuditEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_AuditEvent.DiscardUnknown(m)
}

var xxx_messageInfo_AuditEvent proto.InternalMessageInfo

func (m *AuditEvent) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *AuditEvent) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func init() {
	proto.RegisterType((*AuditEvent)(nil), "events.AuditEvent")
}

func init() { proto.RegisterFile("events.proto", fileDescriptor_8f22242cb04491f9) }

var fileDescriptor_8f22242cb04491f9 = []byte{
	// 110 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x2d, 0x4b, 0xcd,
	0x2b, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0x9c, 0xb9, 0xb8,
	0x1c, 0x4b, 0x53, 0x32, 0x4b, 0x5c, 0x41, 0x5c, 0x21, 0x59, 0x2e, 0xae, 0xc4, 0xe4, 0xe4, 0xfc,
	0xd2, 0xbc, 0x92, 0xf8, 0xcc, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x4e, 0xa8, 0x88,
	0x67, 0x8a, 0x90, 0x18, 0x17, 0x5b, 0x6e, 0x6a, 0x49, 0x46, 0x7e, 0x8a, 0x04, 0x13, 0x58, 0x0a,
	0xca, 0x73, 0xe2, 0x88, 0x62, 0xd3, 0xd3, 0xb7, 0x4e, 0x2c, 0x2f, 0x4e, 0x62, 0x03, 0x9b, 0x6e,
	0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xd6, 0xd4, 0x72, 0x60, 0x6d, 0x00, 0x00, 0x00,
}
