// Code generated by protoc-gen-go. DO NOT EDIT.
// source: iam.proto

package aws

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Credentials struct {
	AccessKeyId          string   `protobuf:"bytes,1,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	SecretAccessKey      string   `protobuf:"bytes,2,opt,name=secret_access_key,json=secretAccessKey,proto3" json:"secret_access_key,omitempty"`
	Region               string   `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Credentials) Reset()         { *m = Credentials{} }
func (m *Credentials) String() string { return proto.CompactTextString(m) }
func (*Credentials) ProtoMessage()    {}
func (*Credentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{0}
}

func (m *Credentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credentials.Unmarshal(m, b)
}
func (m *Credentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credentials.Marshal(b, m, deterministic)
}
func (m *Credentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credentials.Merge(m, src)
}
func (m *Credentials) XXX_Size() int {
	return xxx_messageInfo_Credentials.Size(m)
}
func (m *Credentials) XXX_DiscardUnknown() {
	xxx_messageInfo_Credentials.DiscardUnknown(m)
}

var xxx_messageInfo_Credentials proto.InternalMessageInfo

func (m *Credentials) GetAccessKeyId() string {
	if m != nil {
		return m.AccessKeyId
	}
	return ""
}

func (m *Credentials) GetSecretAccessKey() string {
	if m != nil {
		return m.SecretAccessKey
	}
	return ""
}

func (m *Credentials) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

type User struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string         `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Arn                  string         `protobuf:"bytes,3,opt,name=arn,proto3" json:"arn,omitempty"`
	Credentials          []*Credentials `protobuf:"bytes,4,rep,name=credentials,proto3" json:"credentials,omitempty"`
	Policies             []*Policy      `protobuf:"bytes,5,rep,name=policies,proto3" json:"policies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *User) GetArn() string {
	if m != nil {
		return m.Arn
	}
	return ""
}

func (m *User) GetCredentials() []*Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

func (m *User) GetPolicies() []*Policy {
	if m != nil {
		return m.Policies
	}
	return nil
}

type Policy struct {
	Policy               string   `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Policy) Reset()         { *m = Policy{} }
func (m *Policy) String() string { return proto.CompactTextString(m) }
func (*Policy) ProtoMessage()    {}
func (*Policy) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{2}
}

func (m *Policy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Policy.Unmarshal(m, b)
}
func (m *Policy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Policy.Marshal(b, m, deterministic)
}
func (m *Policy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Policy.Merge(m, src)
}
func (m *Policy) XXX_Size() int {
	return xxx_messageInfo_Policy.Size(m)
}
func (m *Policy) XXX_DiscardUnknown() {
	xxx_messageInfo_Policy.DiscardUnknown(m)
}

var xxx_messageInfo_Policy proto.InternalMessageInfo

func (m *Policy) GetPolicy() string {
	if m != nil {
		return m.Policy
	}
	return ""
}

type CreateUserRequest struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string    `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Policies             []*Policy `protobuf:"bytes,3,rep,name=policies,proto3" json:"policies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{3}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateUserRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateUserRequest) GetPolicies() []*Policy {
	if m != nil {
		return m.Policies
	}
	return nil
}

type CreateUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{4}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*Credentials)(nil), "iam.Credentials")
	proto.RegisterType((*User)(nil), "iam.User")
	proto.RegisterType((*Policy)(nil), "iam.Policy")
	proto.RegisterType((*CreateUserRequest)(nil), "iam.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "iam.CreateUserResponse")
}

func init() {
	proto.RegisterFile("iam.proto", fileDescriptor_0a2c201915207782)
}

var fileDescriptor_0a2c201915207782 = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0xb5, 0x26, 0x86, 0x76, 0x16, 0xb1, 0x9d, 0x43, 0x0d, 0x82, 0x10, 0x72, 0xb1, 0x78, 0xa8,
	0x90, 0x1e, 0x3d, 0x48, 0xed, 0xa9, 0x48, 0x41, 0x22, 0x5e, 0xbc, 0x94, 0x75, 0x33, 0xc8, 0x62,
	0x9b, 0xc4, 0x9d, 0x54, 0xc9, 0x37, 0xf9, 0x93, 0x92, 0x4d, 0x6a, 0x22, 0x82, 0x07, 0x6f, 0x33,
	0x6f, 0xde, 0x9b, 0x37, 0x6f, 0x59, 0x18, 0x68, 0xb9, 0x9d, 0xe6, 0x26, 0x2b, 0x32, 0x74, 0xb4,
	0xdc, 0x86, 0x3b, 0x10, 0x0b, 0x43, 0x09, 0xa5, 0x85, 0x96, 0x1b, 0xc6, 0x10, 0x8e, 0xa5, 0x52,
	0xc4, 0xbc, 0x7e, 0xa5, 0x72, 0xad, 0x13, 0xbf, 0x17, 0xf4, 0x26, 0x83, 0x58, 0xd4, 0xe0, 0x1d,
	0x95, 0xcb, 0x04, 0x2f, 0x61, 0xc4, 0xa4, 0x0c, 0x15, 0xeb, 0x96, 0xea, 0x1f, 0x5a, 0xde, 0x49,
	0x3d, 0x98, 0xef, 0xd9, 0x38, 0x06, 0xcf, 0xd0, 0x8b, 0xce, 0x52, 0xdf, 0xb1, 0x84, 0xa6, 0x0b,
	0x3f, 0x7b, 0xe0, 0x3e, 0x32, 0x19, 0x44, 0x70, 0x53, 0xb9, 0xa5, 0xc6, 0xc7, 0xd6, 0x18, 0x80,
	0x48, 0x88, 0x95, 0xd1, 0x79, 0x51, 0x29, 0xeb, 0xd5, 0x5d, 0x08, 0x87, 0xe0, 0x48, 0xb3, 0xdf,
	0x59, 0x95, 0x18, 0x81, 0x50, 0x6d, 0x0e, 0xdf, 0x0d, 0x9c, 0x89, 0x88, 0x86, 0xd3, 0x2a, 0x6d,
	0x27, 0x5f, 0xdc, 0x25, 0xe1, 0x05, 0xf4, 0xf3, 0x6c, 0xa3, 0x95, 0x26, 0xf6, 0x8f, 0xac, 0x40,
	0x58, 0xc1, 0x7d, 0x05, 0x96, 0xf1, 0xf7, 0x30, 0x0c, 0xc0, 0xab, 0xb1, 0x2a, 0x8f, 0x45, 0xcb,
	0xe6, 0xe0, 0xa6, 0x0b, 0x0d, 0x8c, 0x16, 0x86, 0x64, 0x41, 0x55, 0xa8, 0x98, 0xde, 0x76, 0xc4,
	0xc5, 0x3f, 0xb3, 0x75, 0xaf, 0x72, 0xfe, 0xba, 0x6a, 0x06, 0xd8, 0xf5, 0xe4, 0x3c, 0x4b, 0x99,
	0xf0, 0x1c, 0xdc, 0x1d, 0x93, 0xb1, 0xa6, 0x22, 0x1a, 0x58, 0xa9, 0x25, 0x58, 0x38, 0x5a, 0x01,
	0x2c, 0xe7, 0xab, 0x07, 0x32, 0xef, 0x5a, 0x11, 0xde, 0x00, 0xb4, 0x2b, 0x70, 0xbc, 0x7f, 0xae,
	0x9f, 0x39, 0xce, 0x4e, 0x7f, 0xe1, 0xb5, 0x57, 0x78, 0x70, 0xdb, 0x7f, 0xf2, 0xa6, 0x57, 0xd7,
	0xf2, 0x83, 0x9f, 0x3d, 0xfb, 0xa9, 0x66, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x68, 0xaf, 0x4d,
	0xa6, 0x61, 0x02, 0x00, 0x00,
}
