// Code generated by protoc-gen-go. DO NOT EDIT.
// source: iam.proto

package aws

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Policy struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Manifest             string   `protobuf:"bytes,3,opt,name=manifest,proto3" json:"manifest,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Policy) Reset()         { *m = Policy{} }
func (m *Policy) String() string { return proto.CompactTextString(m) }
func (*Policy) ProtoMessage()    {}
func (*Policy) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{0}
}

func (m *Policy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Policy.Unmarshal(m, b)
}
func (m *Policy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Policy.Marshal(b, m, deterministic)
}
func (m *Policy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Policy.Merge(m, src)
}
func (m *Policy) XXX_Size() int {
	return xxx_messageInfo_Policy.Size(m)
}
func (m *Policy) XXX_DiscardUnknown() {
	xxx_messageInfo_Policy.DiscardUnknown(m)
}

var xxx_messageInfo_Policy proto.InternalMessageInfo

func (m *Policy) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Policy) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Policy) GetManifest() string {
	if m != nil {
		return m.Manifest
	}
	return ""
}

func (m *Policy) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Role struct {
	Id                   uint32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string    `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Policies             []*Policy `protobuf:"bytes,4,rep,name=policies,proto3" json:"policies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}
func (*Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{1}
}

func (m *Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Role.Unmarshal(m, b)
}
func (m *Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Role.Marshal(b, m, deterministic)
}
func (m *Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Role.Merge(m, src)
}
func (m *Role) XXX_Size() int {
	return xxx_messageInfo_Role.Size(m)
}
func (m *Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Role proto.InternalMessageInfo

func (m *Role) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Role) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Role) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Role) GetPolicies() []*Policy {
	if m != nil {
		return m.Policies
	}
	return nil
}

type User struct {
	Id                   uint32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string    `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Policies             []*Policy `protobuf:"bytes,4,rep,name=policies,proto3" json:"policies,omitempty"`
	AccessKeys           string    `protobuf:"bytes,5,opt,name=access_keys,json=accessKeys,proto3" json:"access_keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{2}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *User) GetPolicies() []*Policy {
	if m != nil {
		return m.Policies
	}
	return nil
}

func (m *User) GetAccessKeys() string {
	if m != nil {
		return m.AccessKeys
	}
	return ""
}

type Group struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Users                []*User  `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{3}
}

func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (m *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(m, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Group) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Group) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type AccessKeys struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccessKeys) Reset()         { *m = AccessKeys{} }
func (m *AccessKeys) String() string { return proto.CompactTextString(m) }
func (*AccessKeys) ProtoMessage()    {}
func (*AccessKeys) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{4}
}

func (m *AccessKeys) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessKeys.Unmarshal(m, b)
}
func (m *AccessKeys) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessKeys.Marshal(b, m, deterministic)
}
func (m *AccessKeys) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessKeys.Merge(m, src)
}
func (m *AccessKeys) XXX_Size() int {
	return xxx_messageInfo_AccessKeys.Size(m)
}
func (m *AccessKeys) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessKeys.DiscardUnknown(m)
}

var xxx_messageInfo_AccessKeys proto.InternalMessageInfo

func (m *AccessKeys) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type LoginRequest struct {
	RootUser             bool     `protobuf:"varint,1,opt,name=root_user,json=rootUser,proto3" json:"root_user,omitempty"`
	AccountId            string   `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{5}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetRootUser() bool {
	if m != nil {
		return m.RootUser
	}
	return false
}

func (m *LoginRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SignUpRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	ConfirmPassword      string   `protobuf:"bytes,3,opt,name=confirm_password,json=confirmPassword,proto3" json:"confirm_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpRequest) Reset()         { *m = SignUpRequest{} }
func (m *SignUpRequest) String() string { return proto.CompactTextString(m) }
func (*SignUpRequest) ProtoMessage()    {}
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{6}
}

func (m *SignUpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpRequest.Unmarshal(m, b)
}
func (m *SignUpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpRequest.Marshal(b, m, deterministic)
}
func (m *SignUpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpRequest.Merge(m, src)
}
func (m *SignUpRequest) XXX_Size() int {
	return xxx_messageInfo_SignUpRequest.Size(m)
}
func (m *SignUpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpRequest proto.InternalMessageInfo

func (m *SignUpRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignUpRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *SignUpRequest) GetConfirmPassword() string {
	if m != nil {
		return m.ConfirmPassword
	}
	return ""
}

type SignUpResponse struct {
	Succeed              bool     `protobuf:"varint,1,opt,name=succeed,proto3" json:"succeed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpResponse) Reset()         { *m = SignUpResponse{} }
func (m *SignUpResponse) String() string { return proto.CompactTextString(m) }
func (*SignUpResponse) ProtoMessage()    {}
func (*SignUpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{7}
}

func (m *SignUpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpResponse.Unmarshal(m, b)
}
func (m *SignUpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpResponse.Marshal(b, m, deterministic)
}
func (m *SignUpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpResponse.Merge(m, src)
}
func (m *SignUpResponse) XXX_Size() int {
	return xxx_messageInfo_SignUpResponse.Size(m)
}
func (m *SignUpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpResponse proto.InternalMessageInfo

func (m *SignUpResponse) GetSucceed() bool {
	if m != nil {
		return m.Succeed
	}
	return false
}

type LoginResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{8}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type CreatePolicyRequest struct {
	Policy               *Policy  `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePolicyRequest) Reset()         { *m = CreatePolicyRequest{} }
func (m *CreatePolicyRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePolicyRequest) ProtoMessage()    {}
func (*CreatePolicyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{9}
}

func (m *CreatePolicyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePolicyRequest.Unmarshal(m, b)
}
func (m *CreatePolicyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePolicyRequest.Marshal(b, m, deterministic)
}
func (m *CreatePolicyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePolicyRequest.Merge(m, src)
}
func (m *CreatePolicyRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePolicyRequest.Size(m)
}
func (m *CreatePolicyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePolicyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePolicyRequest proto.InternalMessageInfo

func (m *CreatePolicyRequest) GetPolicy() *Policy {
	if m != nil {
		return m.Policy
	}
	return nil
}

type CreatePolicyResponse struct {
	Created              *Policy  `protobuf:"bytes,1,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePolicyResponse) Reset()         { *m = CreatePolicyResponse{} }
func (m *CreatePolicyResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePolicyResponse) ProtoMessage()    {}
func (*CreatePolicyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{10}
}

func (m *CreatePolicyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePolicyResponse.Unmarshal(m, b)
}
func (m *CreatePolicyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePolicyResponse.Marshal(b, m, deterministic)
}
func (m *CreatePolicyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePolicyResponse.Merge(m, src)
}
func (m *CreatePolicyResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePolicyResponse.Size(m)
}
func (m *CreatePolicyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePolicyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePolicyResponse proto.InternalMessageInfo

func (m *CreatePolicyResponse) GetCreated() *Policy {
	if m != nil {
		return m.Created
	}
	return nil
}

type GetPolicyRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPolicyRequest) Reset()         { *m = GetPolicyRequest{} }
func (m *GetPolicyRequest) String() string { return proto.CompactTextString(m) }
func (*GetPolicyRequest) ProtoMessage()    {}
func (*GetPolicyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{11}
}

func (m *GetPolicyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPolicyRequest.Unmarshal(m, b)
}
func (m *GetPolicyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPolicyRequest.Marshal(b, m, deterministic)
}
func (m *GetPolicyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPolicyRequest.Merge(m, src)
}
func (m *GetPolicyRequest) XXX_Size() int {
	return xxx_messageInfo_GetPolicyRequest.Size(m)
}
func (m *GetPolicyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPolicyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPolicyRequest proto.InternalMessageInfo

func (m *GetPolicyRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetPolicyResponse struct {
	Policy               *Policy  `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPolicyResponse) Reset()         { *m = GetPolicyResponse{} }
func (m *GetPolicyResponse) String() string { return proto.CompactTextString(m) }
func (*GetPolicyResponse) ProtoMessage()    {}
func (*GetPolicyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{12}
}

func (m *GetPolicyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPolicyResponse.Unmarshal(m, b)
}
func (m *GetPolicyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPolicyResponse.Marshal(b, m, deterministic)
}
func (m *GetPolicyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPolicyResponse.Merge(m, src)
}
func (m *GetPolicyResponse) XXX_Size() int {
	return xxx_messageInfo_GetPolicyResponse.Size(m)
}
func (m *GetPolicyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPolicyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPolicyResponse proto.InternalMessageInfo

func (m *GetPolicyResponse) GetPolicy() *Policy {
	if m != nil {
		return m.Policy
	}
	return nil
}

type UpdatePolicyRequest struct {
	Updated              *Policy  `protobuf:"bytes,1,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePolicyRequest) Reset()         { *m = UpdatePolicyRequest{} }
func (m *UpdatePolicyRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePolicyRequest) ProtoMessage()    {}
func (*UpdatePolicyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{13}
}

func (m *UpdatePolicyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePolicyRequest.Unmarshal(m, b)
}
func (m *UpdatePolicyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePolicyRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePolicyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePolicyRequest.Merge(m, src)
}
func (m *UpdatePolicyRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePolicyRequest.Size(m)
}
func (m *UpdatePolicyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePolicyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePolicyRequest proto.InternalMessageInfo

func (m *UpdatePolicyRequest) GetUpdated() *Policy {
	if m != nil {
		return m.Updated
	}
	return nil
}

type UpdatePolicyResponse struct {
	Result               *Policy  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePolicyResponse) Reset()         { *m = UpdatePolicyResponse{} }
func (m *UpdatePolicyResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatePolicyResponse) ProtoMessage()    {}
func (*UpdatePolicyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{14}
}

func (m *UpdatePolicyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePolicyResponse.Unmarshal(m, b)
}
func (m *UpdatePolicyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePolicyResponse.Marshal(b, m, deterministic)
}
func (m *UpdatePolicyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePolicyResponse.Merge(m, src)
}
func (m *UpdatePolicyResponse) XXX_Size() int {
	return xxx_messageInfo_UpdatePolicyResponse.Size(m)
}
func (m *UpdatePolicyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePolicyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePolicyResponse proto.InternalMessageInfo

func (m *UpdatePolicyResponse) GetResult() *Policy {
	if m != nil {
		return m.Result
	}
	return nil
}

type DeletePolicyRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePolicyRequest) Reset()         { *m = DeletePolicyRequest{} }
func (m *DeletePolicyRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePolicyRequest) ProtoMessage()    {}
func (*DeletePolicyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{15}
}

func (m *DeletePolicyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePolicyRequest.Unmarshal(m, b)
}
func (m *DeletePolicyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePolicyRequest.Marshal(b, m, deterministic)
}
func (m *DeletePolicyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePolicyRequest.Merge(m, src)
}
func (m *DeletePolicyRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePolicyRequest.Size(m)
}
func (m *DeletePolicyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePolicyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePolicyRequest proto.InternalMessageInfo

func (m *DeletePolicyRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeletePolicyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePolicyResponse) Reset()         { *m = DeletePolicyResponse{} }
func (m *DeletePolicyResponse) String() string { return proto.CompactTextString(m) }
func (*DeletePolicyResponse) ProtoMessage()    {}
func (*DeletePolicyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{16}
}

func (m *DeletePolicyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePolicyResponse.Unmarshal(m, b)
}
func (m *DeletePolicyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePolicyResponse.Marshal(b, m, deterministic)
}
func (m *DeletePolicyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePolicyResponse.Merge(m, src)
}
func (m *DeletePolicyResponse) XXX_Size() int {
	return xxx_messageInfo_DeletePolicyResponse.Size(m)
}
func (m *DeletePolicyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePolicyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePolicyResponse proto.InternalMessageInfo

type CreateRoleRequest struct {
	Role                 *Role    `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoleRequest) Reset()         { *m = CreateRoleRequest{} }
func (m *CreateRoleRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRoleRequest) ProtoMessage()    {}
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{17}
}

func (m *CreateRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoleRequest.Unmarshal(m, b)
}
func (m *CreateRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoleRequest.Marshal(b, m, deterministic)
}
func (m *CreateRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoleRequest.Merge(m, src)
}
func (m *CreateRoleRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRoleRequest.Size(m)
}
func (m *CreateRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoleRequest proto.InternalMessageInfo

func (m *CreateRoleRequest) GetRole() *Role {
	if m != nil {
		return m.Role
	}
	return nil
}

type CreateRoleResponse struct {
	Created              *Role    `protobuf:"bytes,1,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoleResponse) Reset()         { *m = CreateRoleResponse{} }
func (m *CreateRoleResponse) String() string { return proto.CompactTextString(m) }
func (*CreateRoleResponse) ProtoMessage()    {}
func (*CreateRoleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{18}
}

func (m *CreateRoleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoleResponse.Unmarshal(m, b)
}
func (m *CreateRoleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoleResponse.Marshal(b, m, deterministic)
}
func (m *CreateRoleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoleResponse.Merge(m, src)
}
func (m *CreateRoleResponse) XXX_Size() int {
	return xxx_messageInfo_CreateRoleResponse.Size(m)
}
func (m *CreateRoleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoleResponse proto.InternalMessageInfo

func (m *CreateRoleResponse) GetCreated() *Role {
	if m != nil {
		return m.Created
	}
	return nil
}

type GetRoleRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRoleRequest) Reset()         { *m = GetRoleRequest{} }
func (m *GetRoleRequest) String() string { return proto.CompactTextString(m) }
func (*GetRoleRequest) ProtoMessage()    {}
func (*GetRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{19}
}

func (m *GetRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRoleRequest.Unmarshal(m, b)
}
func (m *GetRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRoleRequest.Marshal(b, m, deterministic)
}
func (m *GetRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRoleRequest.Merge(m, src)
}
func (m *GetRoleRequest) XXX_Size() int {
	return xxx_messageInfo_GetRoleRequest.Size(m)
}
func (m *GetRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRoleRequest proto.InternalMessageInfo

func (m *GetRoleRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetRoleResponse struct {
	Role                 *Role    `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRoleResponse) Reset()         { *m = GetRoleResponse{} }
func (m *GetRoleResponse) String() string { return proto.CompactTextString(m) }
func (*GetRoleResponse) ProtoMessage()    {}
func (*GetRoleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{20}
}

func (m *GetRoleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRoleResponse.Unmarshal(m, b)
}
func (m *GetRoleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRoleResponse.Marshal(b, m, deterministic)
}
func (m *GetRoleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRoleResponse.Merge(m, src)
}
func (m *GetRoleResponse) XXX_Size() int {
	return xxx_messageInfo_GetRoleResponse.Size(m)
}
func (m *GetRoleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRoleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRoleResponse proto.InternalMessageInfo

func (m *GetRoleResponse) GetRole() *Role {
	if m != nil {
		return m.Role
	}
	return nil
}

type UpdateRoleRequest struct {
	Updated              *Role    `protobuf:"bytes,1,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRoleRequest) Reset()         { *m = UpdateRoleRequest{} }
func (m *UpdateRoleRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRoleRequest) ProtoMessage()    {}
func (*UpdateRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{21}
}

func (m *UpdateRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRoleRequest.Unmarshal(m, b)
}
func (m *UpdateRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRoleRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRoleRequest.Merge(m, src)
}
func (m *UpdateRoleRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRoleRequest.Size(m)
}
func (m *UpdateRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRoleRequest proto.InternalMessageInfo

func (m *UpdateRoleRequest) GetUpdated() *Role {
	if m != nil {
		return m.Updated
	}
	return nil
}

type UpdateRoleResponse struct {
	Result               *Role    `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRoleResponse) Reset()         { *m = UpdateRoleResponse{} }
func (m *UpdateRoleResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateRoleResponse) ProtoMessage()    {}
func (*UpdateRoleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{22}
}

func (m *UpdateRoleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRoleResponse.Unmarshal(m, b)
}
func (m *UpdateRoleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRoleResponse.Marshal(b, m, deterministic)
}
func (m *UpdateRoleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRoleResponse.Merge(m, src)
}
func (m *UpdateRoleResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateRoleResponse.Size(m)
}
func (m *UpdateRoleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRoleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRoleResponse proto.InternalMessageInfo

func (m *UpdateRoleResponse) GetResult() *Role {
	if m != nil {
		return m.Result
	}
	return nil
}

type DeleteRoleRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRoleRequest) Reset()         { *m = DeleteRoleRequest{} }
func (m *DeleteRoleRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRoleRequest) ProtoMessage()    {}
func (*DeleteRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{23}
}

func (m *DeleteRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRoleRequest.Unmarshal(m, b)
}
func (m *DeleteRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRoleRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRoleRequest.Merge(m, src)
}
func (m *DeleteRoleRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRoleRequest.Size(m)
}
func (m *DeleteRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRoleRequest proto.InternalMessageInfo

func (m *DeleteRoleRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteRoleResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRoleResponse) Reset()         { *m = DeleteRoleResponse{} }
func (m *DeleteRoleResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteRoleResponse) ProtoMessage()    {}
func (*DeleteRoleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{24}
}

func (m *DeleteRoleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRoleResponse.Unmarshal(m, b)
}
func (m *DeleteRoleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRoleResponse.Marshal(b, m, deterministic)
}
func (m *DeleteRoleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRoleResponse.Merge(m, src)
}
func (m *DeleteRoleResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteRoleResponse.Size(m)
}
func (m *DeleteRoleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRoleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRoleResponse proto.InternalMessageInfo

type CreateUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{25}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateUserResponse struct {
	Created              *User    `protobuf:"bytes,1,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{26}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetCreated() *User {
	if m != nil {
		return m.Created
	}
	return nil
}

type GetUserRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{27}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{28}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserRequest struct {
	Updated              *User    `protobuf:"bytes,1,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{29}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUpdated() *User {
	if m != nil {
		return m.Updated
	}
	return nil
}

type UpdateUserResponse struct {
	Result               *User    `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{30}
}

func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(m, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

func (m *UpdateUserResponse) GetResult() *User {
	if m != nil {
		return m.Result
	}
	return nil
}

type DeleteUserRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{31}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteUserResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserResponse) Reset()         { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()    {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{32}
}

func (m *DeleteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserResponse.Unmarshal(m, b)
}
func (m *DeleteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserResponse.Marshal(b, m, deterministic)
}
func (m *DeleteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserResponse.Merge(m, src)
}
func (m *DeleteUserResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUserResponse.Size(m)
}
func (m *DeleteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserResponse proto.InternalMessageInfo

type CreateGroupRequest struct {
	Group                *Group   `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGroupRequest) Reset()         { *m = CreateGroupRequest{} }
func (m *CreateGroupRequest) String() string { return proto.CompactTextString(m) }
func (*CreateGroupRequest) ProtoMessage()    {}
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{33}
}

func (m *CreateGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGroupRequest.Unmarshal(m, b)
}
func (m *CreateGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGroupRequest.Marshal(b, m, deterministic)
}
func (m *CreateGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGroupRequest.Merge(m, src)
}
func (m *CreateGroupRequest) XXX_Size() int {
	return xxx_messageInfo_CreateGroupRequest.Size(m)
}
func (m *CreateGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGroupRequest proto.InternalMessageInfo

func (m *CreateGroupRequest) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

type CreateGroupResponse struct {
	Created              *Group   `protobuf:"bytes,1,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGroupResponse) Reset()         { *m = CreateGroupResponse{} }
func (m *CreateGroupResponse) String() string { return proto.CompactTextString(m) }
func (*CreateGroupResponse) ProtoMessage()    {}
func (*CreateGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{34}
}

func (m *CreateGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGroupResponse.Unmarshal(m, b)
}
func (m *CreateGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGroupResponse.Marshal(b, m, deterministic)
}
func (m *CreateGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGroupResponse.Merge(m, src)
}
func (m *CreateGroupResponse) XXX_Size() int {
	return xxx_messageInfo_CreateGroupResponse.Size(m)
}
func (m *CreateGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGroupResponse proto.InternalMessageInfo

func (m *CreateGroupResponse) GetCreated() *Group {
	if m != nil {
		return m.Created
	}
	return nil
}

type GetGroupRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupRequest) Reset()         { *m = GetGroupRequest{} }
func (m *GetGroupRequest) String() string { return proto.CompactTextString(m) }
func (*GetGroupRequest) ProtoMessage()    {}
func (*GetGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{35}
}

func (m *GetGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupRequest.Unmarshal(m, b)
}
func (m *GetGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupRequest.Marshal(b, m, deterministic)
}
func (m *GetGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupRequest.Merge(m, src)
}
func (m *GetGroupRequest) XXX_Size() int {
	return xxx_messageInfo_GetGroupRequest.Size(m)
}
func (m *GetGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupRequest proto.InternalMessageInfo

func (m *GetGroupRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetGroupResponse struct {
	Group                *Group   `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupResponse) Reset()         { *m = GetGroupResponse{} }
func (m *GetGroupResponse) String() string { return proto.CompactTextString(m) }
func (*GetGroupResponse) ProtoMessage()    {}
func (*GetGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{36}
}

func (m *GetGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupResponse.Unmarshal(m, b)
}
func (m *GetGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupResponse.Marshal(b, m, deterministic)
}
func (m *GetGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupResponse.Merge(m, src)
}
func (m *GetGroupResponse) XXX_Size() int {
	return xxx_messageInfo_GetGroupResponse.Size(m)
}
func (m *GetGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupResponse proto.InternalMessageInfo

func (m *GetGroupResponse) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

type UpdateGroupRequest struct {
	Updated              *Group   `protobuf:"bytes,1,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateGroupRequest) Reset()         { *m = UpdateGroupRequest{} }
func (m *UpdateGroupRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateGroupRequest) ProtoMessage()    {}
func (*UpdateGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{37}
}

func (m *UpdateGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateGroupRequest.Unmarshal(m, b)
}
func (m *UpdateGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateGroupRequest.Marshal(b, m, deterministic)
}
func (m *UpdateGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateGroupRequest.Merge(m, src)
}
func (m *UpdateGroupRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateGroupRequest.Size(m)
}
func (m *UpdateGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateGroupRequest proto.InternalMessageInfo

func (m *UpdateGroupRequest) GetUpdated() *Group {
	if m != nil {
		return m.Updated
	}
	return nil
}

type UpdateGroupResponse struct {
	Result               *Group   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateGroupResponse) Reset()         { *m = UpdateGroupResponse{} }
func (m *UpdateGroupResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateGroupResponse) ProtoMessage()    {}
func (*UpdateGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{38}
}

func (m *UpdateGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateGroupResponse.Unmarshal(m, b)
}
func (m *UpdateGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateGroupResponse.Marshal(b, m, deterministic)
}
func (m *UpdateGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateGroupResponse.Merge(m, src)
}
func (m *UpdateGroupResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateGroupResponse.Size(m)
}
func (m *UpdateGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateGroupResponse proto.InternalMessageInfo

func (m *UpdateGroupResponse) GetResult() *Group {
	if m != nil {
		return m.Result
	}
	return nil
}

type DeleteGroupRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteGroupRequest) Reset()         { *m = DeleteGroupRequest{} }
func (m *DeleteGroupRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteGroupRequest) ProtoMessage()    {}
func (*DeleteGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{39}
}

func (m *DeleteGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteGroupRequest.Unmarshal(m, b)
}
func (m *DeleteGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteGroupRequest.Marshal(b, m, deterministic)
}
func (m *DeleteGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteGroupRequest.Merge(m, src)
}
func (m *DeleteGroupRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteGroupRequest.Size(m)
}
func (m *DeleteGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteGroupRequest proto.InternalMessageInfo

func (m *DeleteGroupRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteGroupResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteGroupResponse) Reset()         { *m = DeleteGroupResponse{} }
func (m *DeleteGroupResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteGroupResponse) ProtoMessage()    {}
func (*DeleteGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{40}
}

func (m *DeleteGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteGroupResponse.Unmarshal(m, b)
}
func (m *DeleteGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteGroupResponse.Marshal(b, m, deterministic)
}
func (m *DeleteGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteGroupResponse.Merge(m, src)
}
func (m *DeleteGroupResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteGroupResponse.Size(m)
}
func (m *DeleteGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteGroupResponse proto.InternalMessageInfo

type CreateAccessKeysRequest struct {
	AccessKeys           *AccessKeys `protobuf:"bytes,1,opt,name=accessKeys,proto3" json:"accessKeys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateAccessKeysRequest) Reset()         { *m = CreateAccessKeysRequest{} }
func (m *CreateAccessKeysRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccessKeysRequest) ProtoMessage()    {}
func (*CreateAccessKeysRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{41}
}

func (m *CreateAccessKeysRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccessKeysRequest.Unmarshal(m, b)
}
func (m *CreateAccessKeysRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccessKeysRequest.Marshal(b, m, deterministic)
}
func (m *CreateAccessKeysRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccessKeysRequest.Merge(m, src)
}
func (m *CreateAccessKeysRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccessKeysRequest.Size(m)
}
func (m *CreateAccessKeysRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccessKeysRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccessKeysRequest proto.InternalMessageInfo

func (m *CreateAccessKeysRequest) GetAccessKeys() *AccessKeys {
	if m != nil {
		return m.AccessKeys
	}
	return nil
}

type CreateAccessKeysResponse struct {
	Created              *AccessKeys `protobuf:"bytes,1,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateAccessKeysResponse) Reset()         { *m = CreateAccessKeysResponse{} }
func (m *CreateAccessKeysResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAccessKeysResponse) ProtoMessage()    {}
func (*CreateAccessKeysResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{42}
}

func (m *CreateAccessKeysResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccessKeysResponse.Unmarshal(m, b)
}
func (m *CreateAccessKeysResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccessKeysResponse.Marshal(b, m, deterministic)
}
func (m *CreateAccessKeysResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccessKeysResponse.Merge(m, src)
}
func (m *CreateAccessKeysResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAccessKeysResponse.Size(m)
}
func (m *CreateAccessKeysResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccessKeysResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccessKeysResponse proto.InternalMessageInfo

func (m *CreateAccessKeysResponse) GetCreated() *AccessKeys {
	if m != nil {
		return m.Created
	}
	return nil
}

type GetAccessKeysRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccessKeysRequest) Reset()         { *m = GetAccessKeysRequest{} }
func (m *GetAccessKeysRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccessKeysRequest) ProtoMessage()    {}
func (*GetAccessKeysRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{43}
}

func (m *GetAccessKeysRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccessKeysRequest.Unmarshal(m, b)
}
func (m *GetAccessKeysRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccessKeysRequest.Marshal(b, m, deterministic)
}
func (m *GetAccessKeysRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccessKeysRequest.Merge(m, src)
}
func (m *GetAccessKeysRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccessKeysRequest.Size(m)
}
func (m *GetAccessKeysRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccessKeysRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccessKeysRequest proto.InternalMessageInfo

func (m *GetAccessKeysRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetAccessKeysResponse struct {
	AccessKeys           *AccessKeys `protobuf:"bytes,1,opt,name=accessKeys,proto3" json:"accessKeys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetAccessKeysResponse) Reset()         { *m = GetAccessKeysResponse{} }
func (m *GetAccessKeysResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccessKeysResponse) ProtoMessage()    {}
func (*GetAccessKeysResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{44}
}

func (m *GetAccessKeysResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccessKeysResponse.Unmarshal(m, b)
}
func (m *GetAccessKeysResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccessKeysResponse.Marshal(b, m, deterministic)
}
func (m *GetAccessKeysResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccessKeysResponse.Merge(m, src)
}
func (m *GetAccessKeysResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccessKeysResponse.Size(m)
}
func (m *GetAccessKeysResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccessKeysResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccessKeysResponse proto.InternalMessageInfo

func (m *GetAccessKeysResponse) GetAccessKeys() *AccessKeys {
	if m != nil {
		return m.AccessKeys
	}
	return nil
}

type UpdateAccessKeysRequest struct {
	Updated              *AccessKeys `protobuf:"bytes,1,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateAccessKeysRequest) Reset()         { *m = UpdateAccessKeysRequest{} }
func (m *UpdateAccessKeysRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAccessKeysRequest) ProtoMessage()    {}
func (*UpdateAccessKeysRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{45}
}

func (m *UpdateAccessKeysRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAccessKeysRequest.Unmarshal(m, b)
}
func (m *UpdateAccessKeysRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAccessKeysRequest.Marshal(b, m, deterministic)
}
func (m *UpdateAccessKeysRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAccessKeysRequest.Merge(m, src)
}
func (m *UpdateAccessKeysRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAccessKeysRequest.Size(m)
}
func (m *UpdateAccessKeysRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAccessKeysRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAccessKeysRequest proto.InternalMessageInfo

func (m *UpdateAccessKeysRequest) GetUpdated() *AccessKeys {
	if m != nil {
		return m.Updated
	}
	return nil
}

type UpdateAccessKeysResponse struct {
	Result               *AccessKeys `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateAccessKeysResponse) Reset()         { *m = UpdateAccessKeysResponse{} }
func (m *UpdateAccessKeysResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateAccessKeysResponse) ProtoMessage()    {}
func (*UpdateAccessKeysResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{46}
}

func (m *UpdateAccessKeysResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAccessKeysResponse.Unmarshal(m, b)
}
func (m *UpdateAccessKeysResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAccessKeysResponse.Marshal(b, m, deterministic)
}
func (m *UpdateAccessKeysResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAccessKeysResponse.Merge(m, src)
}
func (m *UpdateAccessKeysResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateAccessKeysResponse.Size(m)
}
func (m *UpdateAccessKeysResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAccessKeysResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAccessKeysResponse proto.InternalMessageInfo

func (m *UpdateAccessKeysResponse) GetResult() *AccessKeys {
	if m != nil {
		return m.Result
	}
	return nil
}

type DeleteAccessKeysRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAccessKeysRequest) Reset()         { *m = DeleteAccessKeysRequest{} }
func (m *DeleteAccessKeysRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAccessKeysRequest) ProtoMessage()    {}
func (*DeleteAccessKeysRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{47}
}

func (m *DeleteAccessKeysRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAccessKeysRequest.Unmarshal(m, b)
}
func (m *DeleteAccessKeysRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAccessKeysRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAccessKeysRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAccessKeysRequest.Merge(m, src)
}
func (m *DeleteAccessKeysRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAccessKeysRequest.Size(m)
}
func (m *DeleteAccessKeysRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAccessKeysRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAccessKeysRequest proto.InternalMessageInfo

func (m *DeleteAccessKeysRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteAccessKeysResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAccessKeysResponse) Reset()         { *m = DeleteAccessKeysResponse{} }
func (m *DeleteAccessKeysResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAccessKeysResponse) ProtoMessage()    {}
func (*DeleteAccessKeysResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{48}
}

func (m *DeleteAccessKeysResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAccessKeysResponse.Unmarshal(m, b)
}
func (m *DeleteAccessKeysResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAccessKeysResponse.Marshal(b, m, deterministic)
}
func (m *DeleteAccessKeysResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAccessKeysResponse.Merge(m, src)
}
func (m *DeleteAccessKeysResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAccessKeysResponse.Size(m)
}
func (m *DeleteAccessKeysResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAccessKeysResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAccessKeysResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Policy)(nil), "iam.Policy")
	proto.RegisterType((*Role)(nil), "iam.Role")
	proto.RegisterType((*User)(nil), "iam.User")
	proto.RegisterType((*Group)(nil), "iam.Group")
	proto.RegisterType((*AccessKeys)(nil), "iam.AccessKeys")
	proto.RegisterType((*LoginRequest)(nil), "iam.LoginRequest")
	proto.RegisterType((*SignUpRequest)(nil), "iam.SignUpRequest")
	proto.RegisterType((*SignUpResponse)(nil), "iam.SignUpResponse")
	proto.RegisterType((*LoginResponse)(nil), "iam.LoginResponse")
	proto.RegisterType((*CreatePolicyRequest)(nil), "iam.CreatePolicyRequest")
	proto.RegisterType((*CreatePolicyResponse)(nil), "iam.CreatePolicyResponse")
	proto.RegisterType((*GetPolicyRequest)(nil), "iam.GetPolicyRequest")
	proto.RegisterType((*GetPolicyResponse)(nil), "iam.GetPolicyResponse")
	proto.RegisterType((*UpdatePolicyRequest)(nil), "iam.UpdatePolicyRequest")
	proto.RegisterType((*UpdatePolicyResponse)(nil), "iam.UpdatePolicyResponse")
	proto.RegisterType((*DeletePolicyRequest)(nil), "iam.DeletePolicyRequest")
	proto.RegisterType((*DeletePolicyResponse)(nil), "iam.DeletePolicyResponse")
	proto.RegisterType((*CreateRoleRequest)(nil), "iam.CreateRoleRequest")
	proto.RegisterType((*CreateRoleResponse)(nil), "iam.CreateRoleResponse")
	proto.RegisterType((*GetRoleRequest)(nil), "iam.GetRoleRequest")
	proto.RegisterType((*GetRoleResponse)(nil), "iam.GetRoleResponse")
	proto.RegisterType((*UpdateRoleRequest)(nil), "iam.UpdateRoleRequest")
	proto.RegisterType((*UpdateRoleResponse)(nil), "iam.UpdateRoleResponse")
	proto.RegisterType((*DeleteRoleRequest)(nil), "iam.DeleteRoleRequest")
	proto.RegisterType((*DeleteRoleResponse)(nil), "iam.DeleteRoleResponse")
	proto.RegisterType((*CreateUserRequest)(nil), "iam.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "iam.CreateUserResponse")
	proto.RegisterType((*GetUserRequest)(nil), "iam.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "iam.GetUserResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "iam.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "iam.UpdateUserResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "iam.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "iam.DeleteUserResponse")
	proto.RegisterType((*CreateGroupRequest)(nil), "iam.CreateGroupRequest")
	proto.RegisterType((*CreateGroupResponse)(nil), "iam.CreateGroupResponse")
	proto.RegisterType((*GetGroupRequest)(nil), "iam.GetGroupRequest")
	proto.RegisterType((*GetGroupResponse)(nil), "iam.GetGroupResponse")
	proto.RegisterType((*UpdateGroupRequest)(nil), "iam.UpdateGroupRequest")
	proto.RegisterType((*UpdateGroupResponse)(nil), "iam.UpdateGroupResponse")
	proto.RegisterType((*DeleteGroupRequest)(nil), "iam.DeleteGroupRequest")
	proto.RegisterType((*DeleteGroupResponse)(nil), "iam.DeleteGroupResponse")
	proto.RegisterType((*CreateAccessKeysRequest)(nil), "iam.CreateAccessKeysRequest")
	proto.RegisterType((*CreateAccessKeysResponse)(nil), "iam.CreateAccessKeysResponse")
	proto.RegisterType((*GetAccessKeysRequest)(nil), "iam.GetAccessKeysRequest")
	proto.RegisterType((*GetAccessKeysResponse)(nil), "iam.GetAccessKeysResponse")
	proto.RegisterType((*UpdateAccessKeysRequest)(nil), "iam.UpdateAccessKeysRequest")
	proto.RegisterType((*UpdateAccessKeysResponse)(nil), "iam.UpdateAccessKeysResponse")
	proto.RegisterType((*DeleteAccessKeysRequest)(nil), "iam.DeleteAccessKeysRequest")
	proto.RegisterType((*DeleteAccessKeysResponse)(nil), "iam.DeleteAccessKeysResponse")
}

func init() {
	proto.RegisterFile("iam.proto", fileDescriptor_0a2c201915207782)
}

var fileDescriptor_0a2c201915207782 = []byte{
	// 1143 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x58, 0x4b, 0x6f, 0xdb, 0x46,
	0x10, 0x86, 0x6c, 0x49, 0x96, 0x46, 0x7e, 0x69, 0x25, 0xdb, 0x0c, 0x1b, 0x23, 0xca, 0xda, 0x6e,
	0xec, 0x1e, 0x9c, 0xd6, 0x0d, 0x9a, 0xc4, 0xae, 0x81, 0xa4, 0x4a, 0xeb, 0xa6, 0x0f, 0x34, 0x50,
	0xe0, 0x4b, 0x2f, 0x86, 0x2a, 0x6d, 0x0c, 0x36, 0x12, 0xa9, 0x92, 0x54, 0x03, 0xff, 0x8b, 0x9e,
	0xfa, 0x9f, 0xfa, 0xaf, 0x0a, 0xee, 0xce, 0x92, 0xb3, 0xbb, 0xf4, 0xa3, 0x40, 0x91, 0x5b, 0x38,
	0x3b, 0x33, 0xdf, 0x63, 0x99, 0x19, 0xd1, 0xd0, 0x0c, 0x86, 0xd3, 0xc3, 0x59, 0x1c, 0xa5, 0x11,
	0x5b, 0x0c, 0x86, 0x53, 0xfe, 0x3b, 0xd4, 0xdf, 0x44, 0x93, 0x60, 0x74, 0xc5, 0x56, 0x61, 0x21,
	0x18, 0x7b, 0x95, 0x5e, 0x65, 0x7f, 0x65, 0xb0, 0x10, 0x8c, 0x19, 0x83, 0x6a, 0x38, 0x9c, 0x0a,
	0x6f, 0xa1, 0x57, 0xd9, 0x6f, 0x0e, 0xe4, 0xbf, 0x99, 0x0f, 0x8d, 0xe9, 0x30, 0x0c, 0xde, 0x89,
	0x24, 0xf5, 0x16, 0x65, 0x3c, 0x7f, 0x66, 0x3d, 0x68, 0x8d, 0x45, 0x32, 0x8a, 0x83, 0x59, 0x1a,
	0x44, 0xa1, 0x57, 0x95, 0xc7, 0x34, 0xc4, 0xe7, 0x50, 0x1d, 0x44, 0x13, 0x71, 0x27, 0x24, 0xab,
	0xdb, 0xa2, 0xd3, 0x8d, 0x3d, 0x82, 0xc6, 0x2c, 0x63, 0x1e, 0x88, 0xc4, 0xab, 0xf6, 0x16, 0xf7,
	0x5b, 0x47, 0xad, 0xc3, 0x4c, 0x9c, 0x92, 0x33, 0xc8, 0x0f, 0xf9, 0xdf, 0x15, 0xa8, 0x9e, 0x27,
	0x22, 0xfe, 0xc8, 0xb8, 0xec, 0x01, 0xb4, 0x86, 0xa3, 0x91, 0x48, 0x92, 0x8b, 0xf7, 0xe2, 0x2a,
	0xf1, 0x6a, 0xb2, 0x15, 0xa8, 0xd0, 0x8f, 0xe2, 0x2a, 0xe1, 0x21, 0xd4, 0xce, 0xe2, 0x68, 0x3e,
	0xfb, 0x9f, 0x88, 0x3d, 0x80, 0xda, 0x3c, 0x11, 0xb1, 0x66, 0xd5, 0x94, 0xac, 0x32, 0xe1, 0x03,
	0x15, 0xe7, 0xf7, 0x01, 0x5e, 0xe6, 0xe8, 0x36, 0x28, 0xff, 0xab, 0x02, 0xcb, 0x3f, 0x45, 0x97,
	0x41, 0x38, 0x10, 0x7f, 0xcc, 0xb3, 0x0b, 0xfd, 0x04, 0x9a, 0x71, 0x14, 0xa5, 0x17, 0x59, 0xb1,
	0xcc, 0x6b, 0x0c, 0x1a, 0x59, 0x40, 0x7a, 0xb9, 0x0d, 0x99, 0x92, 0x68, 0x1e, 0xa6, 0x17, 0xc1,
	0x18, 0x89, 0x36, 0x31, 0xf2, 0x7a, 0xcc, 0xba, 0x50, 0x13, 0xd3, 0x61, 0x30, 0x41, 0x9e, 0xea,
	0x21, 0xd7, 0x55, 0x35, 0x5f, 0xa9, 0xd9, 0x30, 0x49, 0x3e, 0x44, 0xf1, 0x18, 0x2d, 0xca, 0x9f,
	0xf9, 0x04, 0x56, 0xde, 0x06, 0x97, 0xe1, 0xf9, 0x4c, 0x53, 0xca, 0xdb, 0x56, 0x68, 0x5b, 0xda,
	0x62, 0xc1, 0x6c, 0xc1, 0x0e, 0x60, 0x7d, 0x14, 0x85, 0xef, 0x82, 0x78, 0x7a, 0x91, 0xe7, 0x28,
	0x4e, 0x6b, 0x18, 0x7f, 0xa3, 0xd1, 0x3e, 0x83, 0x55, 0x8d, 0x96, 0xcc, 0xa2, 0x30, 0x11, 0xcc,
	0x83, 0xa5, 0x64, 0x3e, 0x1a, 0x09, 0x31, 0x46, 0xfd, 0xfa, 0x91, 0xef, 0xc1, 0x0a, 0x7a, 0x85,
	0xa9, 0x5d, 0xa8, 0xa5, 0xd1, 0x7b, 0x11, 0x6a, 0x66, 0xf2, 0x81, 0x1f, 0x43, 0xa7, 0x1f, 0x8b,
	0x61, 0x2a, 0xf0, 0xe5, 0x40, 0x19, 0x3b, 0x50, 0x97, 0x6f, 0xc9, 0x95, 0xcc, 0xb6, 0x5e, 0x20,
	0x3c, 0xe2, 0xa7, 0xd0, 0x35, 0x6b, 0x11, 0x69, 0x0f, 0x96, 0x46, 0x32, 0x3e, 0x2e, 0xab, 0xd6,
	0x67, 0x9c, 0xc3, 0xfa, 0x99, 0x48, 0x4d, 0x5c, 0xfb, 0xca, 0x9f, 0x41, 0x9b, 0xe4, 0x60, 0xff,
	0x3b, 0x91, 0xfb, 0x1a, 0x3a, 0xe7, 0xb3, 0xb1, 0x23, 0x6c, 0x0f, 0x96, 0xe6, 0x32, 0x5c, 0xce,
	0x0d, 0xcf, 0xf8, 0x09, 0x74, 0xcd, 0xea, 0x02, 0x3a, 0x16, 0xc9, 0x7c, 0x92, 0x96, 0x42, 0xab,
	0x23, 0xbe, 0x07, 0x9d, 0x57, 0x62, 0x22, 0x6c, 0x68, 0x5b, 0xdb, 0x26, 0x74, 0xcd, 0x34, 0x85,
	0xc1, 0x8f, 0xa0, 0xad, 0x6c, 0xcd, 0x46, 0x91, 0x2e, 0xde, 0x86, 0x6a, 0x1c, 0x4d, 0x04, 0xc2,
	0xaa, 0xff, 0x39, 0xf2, 0x5c, 0x86, 0xf9, 0x73, 0x60, 0xb4, 0x26, 0x67, 0x6b, 0x5d, 0x04, 0xa9,
	0xcb, 0xaf, 0xa1, 0x07, 0xab, 0x67, 0x22, 0xa5, 0x58, 0x36, 0xd1, 0xcf, 0x61, 0x2d, 0xcf, 0xc0,
	0xce, 0xb7, 0xd0, 0x79, 0x06, 0x6d, 0x65, 0x1f, 0x6d, 0xbb, 0x63, 0x5b, 0x4f, 0xd9, 0x68, 0xe3,
	0x9f, 0x02, 0xa3, 0x95, 0x08, 0xf7, 0xd0, 0xb2, 0x9d, 0x54, 0x6a, 0xd3, 0x77, 0xa0, 0xad, 0xdc,
	0xbc, 0x49, 0x49, 0x17, 0x18, 0x4d, 0xb2, 0x0d, 0x97, 0xa3, 0xa8, 0x30, 0x3c, 0x1f, 0x2b, 0xc6,
	0xa8, 0x92, 0xe1, 0xc2, 0x70, 0x55, 0x73, 0xb3, 0xe1, 0x32, 0xc7, 0x32, 0x9c, 0x62, 0x95, 0x1b,
	0x6e, 0x74, 0xbe, 0x85, 0x4e, 0x6e, 0x38, 0x6d, 0x7b, 0x8d, 0xe1, 0x8a, 0x8d, 0x63, 0xb8, 0x01,
	0x57, 0x6e, 0xb8, 0x4c, 0x71, 0x0c, 0xbf, 0x49, 0x49, 0x6e, 0x38, 0xed, 0xce, 0xbf, 0xd2, 0xe6,
	0xc9, 0xe5, 0xa2, 0x6b, 0x7b, 0x50, 0xbb, 0xcc, 0x9e, 0x11, 0x12, 0x24, 0xa4, 0xca, 0x50, 0x07,
	0xfc, 0x44, 0x0f, 0x2b, 0xac, 0x43, 0xb2, 0xbb, 0xb6, 0xeb, 0xb4, 0x34, 0xb7, 0xfd, 0xa1, 0x34,
	0xd5, 0x40, 0xb4, 0xd9, 0x3e, 0x91, 0x13, 0xc9, 0x6c, 0x7e, 0x3b, 0xab, 0x63, 0xed, 0xa0, 0xd1,
	0x7b, 0xd7, 0x36, 0xdf, 0x20, 0xa5, 0xdd, 0x7f, 0xae, 0xa7, 0x94, 0x09, 0xca, 0x2d, 0xfb, 0x69,
	0xad, 0xf6, 0x7f, 0x57, 0x5b, 0x7b, 0xa3, 0xa4, 0x0d, 0x3d, 0x8b, 0x0c, 0x00, 0xfe, 0x03, 0x6c,
	0x29, 0x27, 0x8b, 0x75, 0xab, 0x3b, 0x3c, 0x06, 0xf2, 0x0b, 0x00, 0xf1, 0xd7, 0x24, 0x3e, 0xc9,
	0xa5, 0x3f, 0x12, 0xbe, 0x05, 0xcf, 0xed, 0x85, 0x42, 0x0e, 0xec, 0xab, 0x71, 0x3a, 0xe5, 0xf7,
	0xf3, 0x29, 0x74, 0xcf, 0x44, 0xea, 0xf2, 0xb1, 0x15, 0x7d, 0x0f, 0x1b, 0x56, 0x1e, 0x62, 0xfd,
	0x67, 0xe2, 0xaf, 0x60, 0x4b, 0x99, 0xef, 0x82, 0x1e, 0xd8, 0xb7, 0xe7, 0xf2, 0xd6, 0x57, 0xd8,
	0x07, 0xcf, 0xed, 0x82, 0x94, 0x1e, 0x59, 0xf7, 0xe8, 0x74, 0xd1, 0x97, 0x79, 0x00, 0x5b, 0xea,
	0x9a, 0x6e, 0xd7, 0xef, 0x83, 0xe7, 0xa6, 0x2a, 0xbc, 0xa3, 0x7f, 0x00, 0xe0, 0xf5, 0xcb, 0x9f,
	0xdf, 0x8a, 0xf8, 0xcf, 0x60, 0x24, 0x58, 0x1f, 0x96, 0xe9, 0x82, 0x66, 0x9e, 0x84, 0x2f, 0xd9,
	0xf7, 0xfe, 0xbd, 0x92, 0x13, 0xd4, 0x70, 0x0c, 0xcd, 0x7c, 0x05, 0xb3, 0x0d, 0xf5, 0x22, 0x5a,
	0x6b, 0xdb, 0xdf, 0xb4, 0xc3, 0x58, 0xdb, 0x87, 0x65, 0xba, 0x46, 0x91, 0x40, 0xc9, 0x5e, 0x46,
	0x02, 0xa5, 0x3b, 0xb7, 0x0f, 0xcb, 0x74, 0x4f, 0x62, 0x93, 0x92, 0x0d, 0x8b, 0x4d, 0xca, 0x96,
	0x2a, 0x3b, 0x05, 0x28, 0x16, 0x24, 0xdb, 0x24, 0x72, 0xc9, 0xbe, 0xf0, 0xb7, 0x9c, 0x38, 0x96,
	0x3f, 0x81, 0x25, 0x5c, 0x81, 0xac, 0xa3, 0xb5, 0xd2, 0xc2, 0xae, 0x19, 0x2c, 0x40, 0x8b, 0x65,
	0x86, 0xa0, 0xce, 0x5e, 0x44, 0xd0, 0x92, 0xad, 0x77, 0x0a, 0x50, 0x6c, 0x2b, 0x2c, 0x77, 0x76,
	0x1c, 0x96, 0xbb, 0x6b, 0xad, 0x90, 0x2c, 0x7f, 0x0e, 0x53, 0xc9, 0x64, 0x62, 0x1b, 0x92, 0x8d,
	0x15, 0xa0, 0x24, 0xcb, 0xda, 0x5c, 0x32, 0x2d, 0xec, 0x9a, 0x41, 0x5b, 0x32, 0x01, 0x75, 0x36,
	0x93, 0x21, 0xd9, 0x2e, 0x2f, 0xf6, 0x85, 0x21, 0xd9, 0x2d, 0x77, 0x17, 0x0b, 0x7b, 0x01, 0x2d,
	0xb2, 0x20, 0x18, 0xd5, 0x46, 0xa7, 0xa4, 0xef, 0xb9, 0x07, 0xd8, 0xe1, 0x29, 0x34, 0xf4, 0x0a,
	0x60, 0xb9, 0x42, 0xa3, 0x76, 0xc3, 0x8a, 0x16, 0xd0, 0x64, 0x92, 0x33, 0xaa, 0xb0, 0x04, 0xba,
	0x6c, 0xe8, 0xbf, 0x80, 0x16, 0x19, 0xd5, 0x8c, 0x8a, 0x2c, 0xe9, 0x50, 0x32, 0xd5, 0xd9, 0x2f,
	0xb0, 0x6e, 0x4f, 0x62, 0x76, 0x9f, 0x48, 0x75, 0x86, 0x8b, 0xbf, 0x7d, 0xcd, 0x29, 0x36, 0xfc,
	0x0e, 0x56, 0x8c, 0x59, 0xcb, 0xee, 0x69, 0xf1, 0x6e, 0x2b, 0xbf, 0xec, 0xa8, 0x20, 0x66, 0xcf,
	0x2c, 0x24, 0x76, 0xcd, 0xd4, 0x43, 0x62, 0xd7, 0x0d, 0x3a, 0x76, 0x08, 0x35, 0xf9, 0x75, 0xc3,
	0xda, 0x32, 0x8f, 0x7e, 0x15, 0xfa, 0x8c, 0x86, 0x30, 0xff, 0x0b, 0xa8, 0xab, 0x2f, 0x27, 0xa6,
	0x4e, 0x8d, 0x8f, 0x36, 0xbf, 0x63, 0xc4, 0x54, 0xc9, 0x37, 0x8d, 0x5f, 0xeb, 0x87, 0x8f, 0x4f,
	0x86, 0x1f, 0x92, 0xdf, 0xea, 0xf2, 0xaf, 0x11, 0x5f, 0xfe, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x3f,
	0xb5, 0x67, 0x18, 0x9a, 0x10, 0x00, 0x00,
}
