// Code generated by protoc-gen-go. DO NOT EDIT.
// source: iam.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Credentials struct {
	AccessKeyId          string   `protobuf:"bytes,1,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	SecretAccessKey      string   `protobuf:"bytes,2,opt,name=secret_access_key,json=secretAccessKey,proto3" json:"secret_access_key,omitempty"`
	Region               string   `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Credentials) Reset()         { *m = Credentials{} }
func (m *Credentials) String() string { return proto.CompactTextString(m) }
func (*Credentials) ProtoMessage()    {}
func (*Credentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{0}
}

func (m *Credentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credentials.Unmarshal(m, b)
}
func (m *Credentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credentials.Marshal(b, m, deterministic)
}
func (m *Credentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credentials.Merge(m, src)
}
func (m *Credentials) XXX_Size() int {
	return xxx_messageInfo_Credentials.Size(m)
}
func (m *Credentials) XXX_DiscardUnknown() {
	xxx_messageInfo_Credentials.DiscardUnknown(m)
}

var xxx_messageInfo_Credentials proto.InternalMessageInfo

func (m *Credentials) GetAccessKeyId() string {
	if m != nil {
		return m.AccessKeyId
	}
	return ""
}

func (m *Credentials) GetSecretAccessKey() string {
	if m != nil {
		return m.SecretAccessKey
	}
	return ""
}

func (m *Credentials) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

type User struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string         `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Arn                  string         `protobuf:"bytes,3,opt,name=arn,proto3" json:"arn,omitempty"`
	Credentials          []*Credentials `protobuf:"bytes,4,rep,name=credentials,proto3" json:"credentials,omitempty"`
	Policies             []*Policy      `protobuf:"bytes,5,rep,name=policies,proto3" json:"policies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *User) GetArn() string {
	if m != nil {
		return m.Arn
	}
	return ""
}

func (m *User) GetCredentials() []*Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

func (m *User) GetPolicies() []*Policy {
	if m != nil {
		return m.Policies
	}
	return nil
}

type Policy struct {
	Policy               string   `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Policy) Reset()         { *m = Policy{} }
func (m *Policy) String() string { return proto.CompactTextString(m) }
func (*Policy) ProtoMessage()    {}
func (*Policy) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{2}
}

func (m *Policy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Policy.Unmarshal(m, b)
}
func (m *Policy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Policy.Marshal(b, m, deterministic)
}
func (m *Policy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Policy.Merge(m, src)
}
func (m *Policy) XXX_Size() int {
	return xxx_messageInfo_Policy.Size(m)
}
func (m *Policy) XXX_DiscardUnknown() {
	xxx_messageInfo_Policy.DiscardUnknown(m)
}

var xxx_messageInfo_Policy proto.InternalMessageInfo

func (m *Policy) GetPolicy() string {
	if m != nil {
		return m.Policy
	}
	return ""
}

type CreateUserRequest struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string    `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Policies             []*Policy `protobuf:"bytes,3,rep,name=policies,proto3" json:"policies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{3}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateUserRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateUserRequest) GetPolicies() []*Policy {
	if m != nil {
		return m.Policies
	}
	return nil
}

type CreateUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2c201915207782, []int{4}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*Credentials)(nil), "iam.Credentials")
	proto.RegisterType((*User)(nil), "iam.User")
	proto.RegisterType((*Policy)(nil), "iam.Policy")
	proto.RegisterType((*CreateUserRequest)(nil), "iam.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "iam.CreateUserResponse")
}

func init() {
	proto.RegisterFile("iam.proto", fileDescriptor_0a2c201915207782)
}

var fileDescriptor_0a2c201915207782 = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0xb5, 0x26, 0x56, 0x33, 0x8b, 0xd8, 0xce, 0xa1, 0x06, 0x41, 0x08, 0xb9, 0x58, 0x3c, 0xf4,
	0x90, 0x1e, 0x3d, 0x48, 0xed, 0xa9, 0x48, 0x41, 0x22, 0x5e, 0xbc, 0x94, 0x75, 0x33, 0xc8, 0x62,
	0x9b, 0xc4, 0xdd, 0x54, 0xc8, 0x37, 0xf9, 0x93, 0xb2, 0x93, 0xd4, 0x46, 0x04, 0x0f, 0x9e, 0x32,
	0xf3, 0xe6, 0xbd, 0x79, 0xf3, 0xc2, 0x42, 0xa0, 0xe5, 0x66, 0x52, 0x9a, 0xa2, 0x2a, 0xd0, 0xd3,
	0x72, 0x13, 0x6f, 0x41, 0xcc, 0x0d, 0x65, 0x94, 0x57, 0x5a, 0xae, 0x2d, 0xc6, 0x70, 0x2a, 0x95,
	0x22, 0x6b, 0x57, 0x6f, 0x54, 0xaf, 0x74, 0x16, 0xf6, 0xa2, 0xde, 0x38, 0x48, 0x45, 0x03, 0xde,
	0x53, 0xbd, 0xc8, 0xf0, 0x1a, 0x86, 0x96, 0x94, 0xa1, 0x6a, 0xb5, 0xa7, 0x86, 0x87, 0xcc, 0x3b,
	0x6b, 0x06, 0xb3, 0x1d, 0x1b, 0x47, 0xd0, 0x37, 0xf4, 0xaa, 0x8b, 0x3c, 0xf4, 0x98, 0xd0, 0x76,
	0xf1, 0x67, 0x0f, 0xfc, 0x27, 0x4b, 0x06, 0x11, 0xfc, 0x5c, 0x6e, 0xa8, 0xf5, 0xe1, 0x1a, 0x23,
	0x10, 0x19, 0x59, 0x65, 0x74, 0x59, 0x39, 0x65, 0xb3, 0xba, 0x0b, 0xe1, 0x00, 0x3c, 0x69, 0x76,
	0x3b, 0x5d, 0x89, 0x09, 0x08, 0xb5, 0xcf, 0x11, 0xfa, 0x91, 0x37, 0x16, 0xc9, 0x60, 0xe2, 0xd2,
	0x76, 0xf2, 0xa5, 0x5d, 0x12, 0x5e, 0xc1, 0x49, 0x59, 0xac, 0xb5, 0xd2, 0x64, 0xc3, 0x23, 0x16,
	0x08, 0x16, 0x3c, 0x38, 0xb0, 0x4e, 0xbf, 0x87, 0x71, 0x04, 0xfd, 0x06, 0x73, 0x79, 0x18, 0xad,
	0xdb, 0x83, 0xdb, 0x2e, 0x36, 0x30, 0x9c, 0x1b, 0x92, 0x15, 0xb9, 0x50, 0x29, 0xbd, 0x6f, 0xc9,
	0x56, 0xff, 0xcc, 0xd6, 0xbd, 0xca, 0xfb, 0xeb, 0xaa, 0x29, 0x60, 0xd7, 0xd3, 0x96, 0x45, 0x6e,
	0x09, 0x2f, 0xc1, 0xdf, 0x5a, 0x32, 0x6c, 0x2a, 0x92, 0x80, 0xa5, 0x4c, 0x60, 0x38, 0x59, 0x02,
	0x2c, 0x66, 0xcb, 0x47, 0x32, 0x1f, 0x5a, 0x11, 0xde, 0x02, 0xec, 0x57, 0xe0, 0x68, 0xf7, 0xbb,
	0x7e, 0xe6, 0xb8, 0x38, 0xff, 0x85, 0x37, 0x5e, 0xf1, 0xc1, 0x5d, 0xf0, 0x7c, 0x3c, 0xb9, 0xe1,
	0xe7, 0xf4, 0xd2, 0xe7, 0xcf, 0xf4, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xc2, 0x41, 0x99, 0xb9, 0x62,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// IAMServiceClient is the client API for IAMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IAMServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
}

type iAMServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIAMServiceClient(cc grpc.ClientConnInterface) IAMServiceClient {
	return &iAMServiceClient{cc}
}

func (c *iAMServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/iam.IAMService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IAMServiceServer is the server API for IAMService service.
type IAMServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
}

// UnimplementedIAMServiceServer can be embedded to have forward compatible implementations.
type UnimplementedIAMServiceServer struct {
}

func (*UnimplementedIAMServiceServer) CreateUser(ctx context.Context, req *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}

func RegisterIAMServiceServer(s *grpc.Server, srv IAMServiceServer) {
	s.RegisterService(&_IAMService_serviceDesc, srv)
}

func _IAMService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iam.IAMService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _IAMService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "iam.IAMService",
	HandlerType: (*IAMServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _IAMService_CreateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "iam.proto",
}
