// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package aws

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// LambdaServiceClient is the client API for LambdaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LambdaServiceClient interface {
	CreateFunction(ctx context.Context, in *CreateFunctionRequest, opts ...grpc.CallOption) (*LambdaResponse, error)
	TestFunction(ctx context.Context, in *TestFunctionResquest, opts ...grpc.CallOption) (*LambdaResponse, error)
}

type lambdaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLambdaServiceClient(cc grpc.ClientConnInterface) LambdaServiceClient {
	return &lambdaServiceClient{cc}
}

func (c *lambdaServiceClient) CreateFunction(ctx context.Context, in *CreateFunctionRequest, opts ...grpc.CallOption) (*LambdaResponse, error) {
	out := new(LambdaResponse)
	err := c.cc.Invoke(ctx, "/lambda.LambdaService/CreateFunction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lambdaServiceClient) TestFunction(ctx context.Context, in *TestFunctionResquest, opts ...grpc.CallOption) (*LambdaResponse, error) {
	out := new(LambdaResponse)
	err := c.cc.Invoke(ctx, "/lambda.LambdaService/TestFunction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LambdaServiceServer is the server API for LambdaService service.
// All implementations should embed UnimplementedLambdaServiceServer
// for forward compatibility
type LambdaServiceServer interface {
	CreateFunction(context.Context, *CreateFunctionRequest) (*LambdaResponse, error)
	TestFunction(context.Context, *TestFunctionResquest) (*LambdaResponse, error)
}

// UnimplementedLambdaServiceServer should be embedded to have forward compatible implementations.
type UnimplementedLambdaServiceServer struct {
}

func (UnimplementedLambdaServiceServer) CreateFunction(context.Context, *CreateFunctionRequest) (*LambdaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFunction not implemented")
}
func (UnimplementedLambdaServiceServer) TestFunction(context.Context, *TestFunctionResquest) (*LambdaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestFunction not implemented")
}

// UnsafeLambdaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LambdaServiceServer will
// result in compilation errors.
type UnsafeLambdaServiceServer interface {
	mustEmbedUnimplementedLambdaServiceServer()
}

func RegisterLambdaServiceServer(s *grpc.Server, srv LambdaServiceServer) {
	s.RegisterService(&_LambdaService_serviceDesc, srv)
}

func _LambdaService_CreateFunction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFunctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LambdaServiceServer).CreateFunction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lambda.LambdaService/CreateFunction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LambdaServiceServer).CreateFunction(ctx, req.(*CreateFunctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LambdaService_TestFunction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestFunctionResquest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LambdaServiceServer).TestFunction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lambda.LambdaService/TestFunction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LambdaServiceServer).TestFunction(ctx, req.(*TestFunctionResquest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LambdaService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lambda.LambdaService",
	HandlerType: (*LambdaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFunction",
			Handler:    _LambdaService_CreateFunction_Handler,
		},
		{
			MethodName: "TestFunction",
			Handler:    _LambdaService_TestFunction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lambda.proto",
}
