# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lambda.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='lambda.proto',
  package='lambda',
  syntax='proto3',
  serialized_options=b'Z\006./;aws',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0clambda.proto\x12\x06lambda\x1a\x1bgoogle/protobuf/empty.proto\"s\n\x15\x43reateFunctionRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12 \n\x07runtime\x18\x02 \x01(\x0e\x32\x0f.lambda.Runtime\x12\x0b\n\x03ram\x18\x03 \x01(\x05\x12\x0c\n\x04\x63ode\x18\x04 \x01(\t\x12\x0f\n\x07handler\x18\x05 \x01(\t\"-\n\x0eLambdaResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\n\n\x02ok\x18\x02 \x01(\x08\"A\n\x14TestFunctionResquest\x12\x15\n\rfunction_name\x18\x01 \x01(\t\x12\x12\n\nevent_data\x18\x02 \x01(\t\"9\n\x16InvoqueFunctionRequest\x12\x0b\n\x03\x61rn\x18\x01 \x01(\t\x12\x12\n\nevent_data\x18\x02 \x01(\t\"#\n\x13ReceiveEventRequest\x12\x0c\n\x04hash\x18\x01 \x01(\t\" \n\rEventResponse\x12\x0f\n\x07message\x18\x01 \x01(\t*0\n\x07Runtime\x12\x0c\n\x08nodejs14\x10\x00\x12\x0b\n\x07python3\x10\x01\x12\n\n\x06golang\x10\x02\x32\xfe\x02\n\rLambdaService\x12I\n\x0e\x43reateFunction\x12\x1d.lambda.CreateFunctionRequest\x1a\x16.lambda.LambdaResponse\"\x00\x12\x46\n\x0cTestFunction\x12\x1c.lambda.TestFunctionResquest\x1a\x16.lambda.LambdaResponse\"\x00\x12K\n\x0fInvoqueFunction\x12\x1e.lambda.InvoqueFunctionRequest\x1a\x16.lambda.LambdaResponse\"\x00\x12\x44\n\x10SeedLambdaServer\x12\x16.google.protobuf.Empty\x1a\x16.lambda.LambdaResponse\"\x00\x12G\n\rReceiveEvents\x12\x1b.lambda.ReceiveEventRequest\x1a\x15.lambda.EventResponse\"\x00\x30\x01\x42\x08Z\x06./;awsb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])

_RUNTIME = _descriptor.EnumDescriptor(
  name='Runtime',
  full_name='lambda.Runtime',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='nodejs14', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='python3', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='golang', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=414,
  serialized_end=462,
)
_sym_db.RegisterEnumDescriptor(_RUNTIME)

Runtime = enum_type_wrapper.EnumTypeWrapper(_RUNTIME)
nodejs14 = 0
python3 = 1
golang = 2



_CREATEFUNCTIONREQUEST = _descriptor.Descriptor(
  name='CreateFunctionRequest',
  full_name='lambda.CreateFunctionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='lambda.CreateFunctionRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='runtime', full_name='lambda.CreateFunctionRequest.runtime', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ram', full_name='lambda.CreateFunctionRequest.ram', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code', full_name='lambda.CreateFunctionRequest.code', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='handler', full_name='lambda.CreateFunctionRequest.handler', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=168,
)


_LAMBDARESPONSE = _descriptor.Descriptor(
  name='LambdaResponse',
  full_name='lambda.LambdaResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='lambda.LambdaResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ok', full_name='lambda.LambdaResponse.ok', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=215,
)


_TESTFUNCTIONRESQUEST = _descriptor.Descriptor(
  name='TestFunctionResquest',
  full_name='lambda.TestFunctionResquest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='function_name', full_name='lambda.TestFunctionResquest.function_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='event_data', full_name='lambda.TestFunctionResquest.event_data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=282,
)


_INVOQUEFUNCTIONREQUEST = _descriptor.Descriptor(
  name='InvoqueFunctionRequest',
  full_name='lambda.InvoqueFunctionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='arn', full_name='lambda.InvoqueFunctionRequest.arn', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='event_data', full_name='lambda.InvoqueFunctionRequest.event_data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=284,
  serialized_end=341,
)


_RECEIVEEVENTREQUEST = _descriptor.Descriptor(
  name='ReceiveEventRequest',
  full_name='lambda.ReceiveEventRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hash', full_name='lambda.ReceiveEventRequest.hash', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=343,
  serialized_end=378,
)


_EVENTRESPONSE = _descriptor.Descriptor(
  name='EventResponse',
  full_name='lambda.EventResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='lambda.EventResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=380,
  serialized_end=412,
)

_CREATEFUNCTIONREQUEST.fields_by_name['runtime'].enum_type = _RUNTIME
DESCRIPTOR.message_types_by_name['CreateFunctionRequest'] = _CREATEFUNCTIONREQUEST
DESCRIPTOR.message_types_by_name['LambdaResponse'] = _LAMBDARESPONSE
DESCRIPTOR.message_types_by_name['TestFunctionResquest'] = _TESTFUNCTIONRESQUEST
DESCRIPTOR.message_types_by_name['InvoqueFunctionRequest'] = _INVOQUEFUNCTIONREQUEST
DESCRIPTOR.message_types_by_name['ReceiveEventRequest'] = _RECEIVEEVENTREQUEST
DESCRIPTOR.message_types_by_name['EventResponse'] = _EVENTRESPONSE
DESCRIPTOR.enum_types_by_name['Runtime'] = _RUNTIME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateFunctionRequest = _reflection.GeneratedProtocolMessageType('CreateFunctionRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEFUNCTIONREQUEST,
  '__module__' : 'lambda_pb2'
  # @@protoc_insertion_point(class_scope:lambda.CreateFunctionRequest)
  })
_sym_db.RegisterMessage(CreateFunctionRequest)

LambdaResponse = _reflection.GeneratedProtocolMessageType('LambdaResponse', (_message.Message,), {
  'DESCRIPTOR' : _LAMBDARESPONSE,
  '__module__' : 'lambda_pb2'
  # @@protoc_insertion_point(class_scope:lambda.LambdaResponse)
  })
_sym_db.RegisterMessage(LambdaResponse)

TestFunctionResquest = _reflection.GeneratedProtocolMessageType('TestFunctionResquest', (_message.Message,), {
  'DESCRIPTOR' : _TESTFUNCTIONRESQUEST,
  '__module__' : 'lambda_pb2'
  # @@protoc_insertion_point(class_scope:lambda.TestFunctionResquest)
  })
_sym_db.RegisterMessage(TestFunctionResquest)

InvoqueFunctionRequest = _reflection.GeneratedProtocolMessageType('InvoqueFunctionRequest', (_message.Message,), {
  'DESCRIPTOR' : _INVOQUEFUNCTIONREQUEST,
  '__module__' : 'lambda_pb2'
  # @@protoc_insertion_point(class_scope:lambda.InvoqueFunctionRequest)
  })
_sym_db.RegisterMessage(InvoqueFunctionRequest)

ReceiveEventRequest = _reflection.GeneratedProtocolMessageType('ReceiveEventRequest', (_message.Message,), {
  'DESCRIPTOR' : _RECEIVEEVENTREQUEST,
  '__module__' : 'lambda_pb2'
  # @@protoc_insertion_point(class_scope:lambda.ReceiveEventRequest)
  })
_sym_db.RegisterMessage(ReceiveEventRequest)

EventResponse = _reflection.GeneratedProtocolMessageType('EventResponse', (_message.Message,), {
  'DESCRIPTOR' : _EVENTRESPONSE,
  '__module__' : 'lambda_pb2'
  # @@protoc_insertion_point(class_scope:lambda.EventResponse)
  })
_sym_db.RegisterMessage(EventResponse)


DESCRIPTOR._options = None

_LAMBDASERVICE = _descriptor.ServiceDescriptor(
  name='LambdaService',
  full_name='lambda.LambdaService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=465,
  serialized_end=847,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateFunction',
    full_name='lambda.LambdaService.CreateFunction',
    index=0,
    containing_service=None,
    input_type=_CREATEFUNCTIONREQUEST,
    output_type=_LAMBDARESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='TestFunction',
    full_name='lambda.LambdaService.TestFunction',
    index=1,
    containing_service=None,
    input_type=_TESTFUNCTIONRESQUEST,
    output_type=_LAMBDARESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='InvoqueFunction',
    full_name='lambda.LambdaService.InvoqueFunction',
    index=2,
    containing_service=None,
    input_type=_INVOQUEFUNCTIONREQUEST,
    output_type=_LAMBDARESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SeedLambdaServer',
    full_name='lambda.LambdaService.SeedLambdaServer',
    index=3,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_LAMBDARESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ReceiveEvents',
    full_name='lambda.LambdaService.ReceiveEvents',
    index=4,
    containing_service=None,
    input_type=_RECEIVEEVENTREQUEST,
    output_type=_EVENTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LAMBDASERVICE)

DESCRIPTOR.services_by_name['LambdaService'] = _LAMBDASERVICE

# @@protoc_insertion_point(module_scope)
