// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lambda.proto

package aws

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Runtime int32

const (
	Runtime_nodejs14 Runtime = 0
	Runtime_python3  Runtime = 1
	Runtime_golang   Runtime = 2
)

var Runtime_name = map[int32]string{
	0: "nodejs14",
	1: "python3",
	2: "golang",
}

var Runtime_value = map[string]int32{
	"nodejs14": 0,
	"python3":  1,
	"golang":   2,
}

func (x Runtime) String() string {
	return proto.EnumName(Runtime_name, int32(x))
}

func (Runtime) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cc06342ed5111805, []int{0}
}

type CreateFunctionRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Runtime              Runtime  `protobuf:"varint,2,opt,name=runtime,proto3,enum=lambda.Runtime" json:"runtime,omitempty"`
	Ram                  int32    `protobuf:"varint,3,opt,name=ram,proto3" json:"ram,omitempty"`
	Code                 string   `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	Handler              string   `protobuf:"bytes,5,opt,name=handler,proto3" json:"handler,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateFunctionRequest) Reset()         { *m = CreateFunctionRequest{} }
func (m *CreateFunctionRequest) String() string { return proto.CompactTextString(m) }
func (*CreateFunctionRequest) ProtoMessage()    {}
func (*CreateFunctionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc06342ed5111805, []int{0}
}

func (m *CreateFunctionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFunctionRequest.Unmarshal(m, b)
}
func (m *CreateFunctionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFunctionRequest.Marshal(b, m, deterministic)
}
func (m *CreateFunctionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFunctionRequest.Merge(m, src)
}
func (m *CreateFunctionRequest) XXX_Size() int {
	return xxx_messageInfo_CreateFunctionRequest.Size(m)
}
func (m *CreateFunctionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFunctionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFunctionRequest proto.InternalMessageInfo

func (m *CreateFunctionRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateFunctionRequest) GetRuntime() Runtime {
	if m != nil {
		return m.Runtime
	}
	return Runtime_nodejs14
}

func (m *CreateFunctionRequest) GetRam() int32 {
	if m != nil {
		return m.Ram
	}
	return 0
}

func (m *CreateFunctionRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CreateFunctionRequest) GetHandler() string {
	if m != nil {
		return m.Handler
	}
	return ""
}

type LambdaResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Ok                   bool     `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LambdaResponse) Reset()         { *m = LambdaResponse{} }
func (m *LambdaResponse) String() string { return proto.CompactTextString(m) }
func (*LambdaResponse) ProtoMessage()    {}
func (*LambdaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc06342ed5111805, []int{1}
}

func (m *LambdaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LambdaResponse.Unmarshal(m, b)
}
func (m *LambdaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LambdaResponse.Marshal(b, m, deterministic)
}
func (m *LambdaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LambdaResponse.Merge(m, src)
}
func (m *LambdaResponse) XXX_Size() int {
	return xxx_messageInfo_LambdaResponse.Size(m)
}
func (m *LambdaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LambdaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LambdaResponse proto.InternalMessageInfo

func (m *LambdaResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *LambdaResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type TestFunctionResquest struct {
	FunctionName         string   `protobuf:"bytes,1,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	EventData            string   `protobuf:"bytes,2,opt,name=event_data,json=eventData,proto3" json:"event_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestFunctionResquest) Reset()         { *m = TestFunctionResquest{} }
func (m *TestFunctionResquest) String() string { return proto.CompactTextString(m) }
func (*TestFunctionResquest) ProtoMessage()    {}
func (*TestFunctionResquest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc06342ed5111805, []int{2}
}

func (m *TestFunctionResquest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestFunctionResquest.Unmarshal(m, b)
}
func (m *TestFunctionResquest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestFunctionResquest.Marshal(b, m, deterministic)
}
func (m *TestFunctionResquest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestFunctionResquest.Merge(m, src)
}
func (m *TestFunctionResquest) XXX_Size() int {
	return xxx_messageInfo_TestFunctionResquest.Size(m)
}
func (m *TestFunctionResquest) XXX_DiscardUnknown() {
	xxx_messageInfo_TestFunctionResquest.DiscardUnknown(m)
}

var xxx_messageInfo_TestFunctionResquest proto.InternalMessageInfo

func (m *TestFunctionResquest) GetFunctionName() string {
	if m != nil {
		return m.FunctionName
	}
	return ""
}

func (m *TestFunctionResquest) GetEventData() string {
	if m != nil {
		return m.EventData
	}
	return ""
}

type InvoqueFunctionRequest struct {
	Arn                  string   `protobuf:"bytes,1,opt,name=arn,proto3" json:"arn,omitempty"`
	EventData            string   `protobuf:"bytes,2,opt,name=event_data,json=eventData,proto3" json:"event_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvoqueFunctionRequest) Reset()         { *m = InvoqueFunctionRequest{} }
func (m *InvoqueFunctionRequest) String() string { return proto.CompactTextString(m) }
func (*InvoqueFunctionRequest) ProtoMessage()    {}
func (*InvoqueFunctionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc06342ed5111805, []int{3}
}

func (m *InvoqueFunctionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvoqueFunctionRequest.Unmarshal(m, b)
}
func (m *InvoqueFunctionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvoqueFunctionRequest.Marshal(b, m, deterministic)
}
func (m *InvoqueFunctionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvoqueFunctionRequest.Merge(m, src)
}
func (m *InvoqueFunctionRequest) XXX_Size() int {
	return xxx_messageInfo_InvoqueFunctionRequest.Size(m)
}
func (m *InvoqueFunctionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InvoqueFunctionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InvoqueFunctionRequest proto.InternalMessageInfo

func (m *InvoqueFunctionRequest) GetArn() string {
	if m != nil {
		return m.Arn
	}
	return ""
}

func (m *InvoqueFunctionRequest) GetEventData() string {
	if m != nil {
		return m.EventData
	}
	return ""
}

type ReceiveEventRequest struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiveEventRequest) Reset()         { *m = ReceiveEventRequest{} }
func (m *ReceiveEventRequest) String() string { return proto.CompactTextString(m) }
func (*ReceiveEventRequest) ProtoMessage()    {}
func (*ReceiveEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc06342ed5111805, []int{4}
}

func (m *ReceiveEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiveEventRequest.Unmarshal(m, b)
}
func (m *ReceiveEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiveEventRequest.Marshal(b, m, deterministic)
}
func (m *ReceiveEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiveEventRequest.Merge(m, src)
}
func (m *ReceiveEventRequest) XXX_Size() int {
	return xxx_messageInfo_ReceiveEventRequest.Size(m)
}
func (m *ReceiveEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiveEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiveEventRequest proto.InternalMessageInfo

func (m *ReceiveEventRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type EventResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventResponse) Reset()         { *m = EventResponse{} }
func (m *EventResponse) String() string { return proto.CompactTextString(m) }
func (*EventResponse) ProtoMessage()    {}
func (*EventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc06342ed5111805, []int{5}
}

func (m *EventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventResponse.Unmarshal(m, b)
}
func (m *EventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventResponse.Marshal(b, m, deterministic)
}
func (m *EventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventResponse.Merge(m, src)
}
func (m *EventResponse) XXX_Size() int {
	return xxx_messageInfo_EventResponse.Size(m)
}
func (m *EventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EventResponse proto.InternalMessageInfo

func (m *EventResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UpdateLambdaRequest struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateLambdaRequest) Reset()         { *m = UpdateLambdaRequest{} }
func (m *UpdateLambdaRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateLambdaRequest) ProtoMessage()    {}
func (*UpdateLambdaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc06342ed5111805, []int{6}
}

func (m *UpdateLambdaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateLambdaRequest.Unmarshal(m, b)
}
func (m *UpdateLambdaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateLambdaRequest.Marshal(b, m, deterministic)
}
func (m *UpdateLambdaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateLambdaRequest.Merge(m, src)
}
func (m *UpdateLambdaRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateLambdaRequest.Size(m)
}
func (m *UpdateLambdaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateLambdaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateLambdaRequest proto.InternalMessageInfo

func (m *UpdateLambdaRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func init() {
	proto.RegisterEnum("lambda.Runtime", Runtime_name, Runtime_value)
	proto.RegisterType((*CreateFunctionRequest)(nil), "lambda.CreateFunctionRequest")
	proto.RegisterType((*LambdaResponse)(nil), "lambda.LambdaResponse")
	proto.RegisterType((*TestFunctionResquest)(nil), "lambda.TestFunctionResquest")
	proto.RegisterType((*InvoqueFunctionRequest)(nil), "lambda.InvoqueFunctionRequest")
	proto.RegisterType((*ReceiveEventRequest)(nil), "lambda.ReceiveEventRequest")
	proto.RegisterType((*EventResponse)(nil), "lambda.EventResponse")
	proto.RegisterType((*UpdateLambdaRequest)(nil), "lambda.UpdateLambdaRequest")
}

func init() {
	proto.RegisterFile("lambda.proto", fileDescriptor_cc06342ed5111805)
}

var fileDescriptor_cc06342ed5111805 = []byte{
	// 498 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xcf, 0x72, 0xd3, 0x30,
	0x10, 0xc6, 0xe3, 0xa4, 0xcd, 0x9f, 0xc5, 0x49, 0x3d, 0x82, 0x66, 0x3c, 0x29, 0x65, 0x32, 0xe6,
	0x92, 0x70, 0x70, 0x4a, 0xcb, 0x09, 0x6e, 0xd0, 0x94, 0xc9, 0xc0, 0x70, 0x70, 0xe1, 0xd2, 0x4b,
	0x47, 0x89, 0xb7, 0x4e, 0x68, 0x2c, 0xb9, 0x96, 0x1c, 0xa6, 0x2f, 0xc2, 0x1b, 0xf1, 0x5e, 0x8c,
	0x64, 0xab, 0x71, 0x68, 0x48, 0x6f, 0xab, 0xd5, 0xce, 0x4f, 0xda, 0xef, 0xdb, 0x05, 0x7b, 0x49,
	0xe3, 0x69, 0x48, 0xfd, 0x24, 0xe5, 0x92, 0x93, 0x7a, 0x7e, 0xea, 0x1d, 0x45, 0x9c, 0x47, 0x4b,
	0x1c, 0xe9, 0xec, 0x34, 0xbb, 0x19, 0x61, 0x9c, 0xc8, 0xfb, 0xbc, 0xc8, 0xfb, 0x6d, 0xc1, 0xe1,
	0xa7, 0x14, 0xa9, 0xc4, 0x8b, 0x8c, 0xcd, 0xe4, 0x82, 0xb3, 0x00, 0xef, 0x32, 0x14, 0x92, 0x10,
	0xd8, 0x63, 0x34, 0x46, 0xd7, 0xea, 0x5b, 0x83, 0x56, 0xa0, 0x63, 0x32, 0x84, 0x46, 0x9a, 0x31,
	0xb9, 0x88, 0xd1, 0xad, 0xf6, 0xad, 0x41, 0xe7, 0xf4, 0xc0, 0x2f, 0x9e, 0x0c, 0xf2, 0x74, 0x60,
	0xee, 0x89, 0x03, 0xb5, 0x94, 0xc6, 0x6e, 0xad, 0x6f, 0x0d, 0xf6, 0x03, 0x15, 0x2a, 0xe0, 0x8c,
	0x87, 0xe8, 0xee, 0xe5, 0x40, 0x15, 0x13, 0x17, 0x1a, 0x73, 0xca, 0xc2, 0x25, 0xa6, 0xee, 0xbe,
	0x4e, 0x9b, 0xa3, 0xf7, 0x1e, 0x3a, 0x5f, 0x35, 0x3a, 0x40, 0x91, 0x70, 0x26, 0x74, 0x6d, 0x8c,
	0x42, 0xd0, 0xc8, 0xfc, 0xc9, 0x1c, 0x49, 0x07, 0xaa, 0xfc, 0x56, 0xff, 0xa8, 0x19, 0x54, 0xf9,
	0xad, 0x77, 0x05, 0x2f, 0xbe, 0xa3, 0x90, 0xeb, 0x8e, 0x44, 0xde, 0xd2, 0x6b, 0x68, 0xdf, 0x14,
	0xb9, 0xeb, 0x52, 0x6f, 0xb6, 0x49, 0x7e, 0x53, 0x3d, 0x1e, 0x03, 0xe0, 0x0a, 0x99, 0xbc, 0x0e,
	0xa9, 0xa4, 0x1a, 0xda, 0x0a, 0x5a, 0x3a, 0x73, 0x4e, 0x25, 0xf5, 0x26, 0xd0, 0x9d, 0xb0, 0x15,
	0xbf, 0xcb, 0x1e, 0x09, 0xe6, 0x40, 0x8d, 0xa6, 0xac, 0x60, 0xaa, 0xf0, 0x29, 0xd4, 0x10, 0x9e,
	0x07, 0x38, 0xc3, 0xc5, 0x0a, 0xc7, 0x2a, 0x57, 0x12, 0x7e, 0x4e, 0xc5, 0xdc, 0x08, 0xaf, 0x62,
	0x6f, 0x08, 0xed, 0xa2, 0xe6, 0x29, 0x31, 0x14, 0xf5, 0x47, 0x12, 0x52, 0x89, 0x46, 0xbe, 0x07,
	0xaa, 0x56, 0xdf, 0x5a, 0xab, 0xff, 0xe6, 0x04, 0x1a, 0x85, 0x6f, 0xc4, 0x86, 0x26, 0xe3, 0x21,
	0xfe, 0x14, 0x6f, 0xdf, 0x39, 0x15, 0xf2, 0x0c, 0x1a, 0xc9, 0xbd, 0x9c, 0x73, 0x76, 0xe6, 0x58,
	0x04, 0xa0, 0x1e, 0xf1, 0x25, 0x65, 0x91, 0x53, 0x3d, 0xfd, 0x53, 0x83, 0x76, 0xce, 0xbd, 0xc4,
	0x74, 0xb5, 0x98, 0x21, 0x99, 0x40, 0x67, 0x73, 0x7e, 0xc8, 0xb1, 0x99, 0x89, 0xad, 0x73, 0xd5,
	0xeb, 0x9a, 0xeb, 0x4d, 0x7b, 0xbd, 0x0a, 0xb9, 0x00, 0xbb, 0x6c, 0x1b, 0x79, 0x69, 0x2a, 0xb7,
	0x99, 0xb9, 0x83, 0xf3, 0x05, 0x0e, 0xfe, 0xb1, 0x88, 0xbc, 0x32, 0xc5, 0xdb, 0xbd, 0xdb, 0x01,
	0x3b, 0x07, 0xe7, 0x12, 0x31, 0x5c, 0x37, 0x8d, 0x29, 0xe9, 0xfa, 0xf9, 0x4a, 0xf9, 0x66, 0xa5,
	0xfc, 0xb1, 0x5a, 0xa9, 0x1d, 0x94, 0xcf, 0xd0, 0x2e, 0x5b, 0x2d, 0xc8, 0xd1, 0xc3, 0xe2, 0x3c,
	0x9e, 0x80, 0xde, 0xa1, 0xb9, 0xdc, 0xf0, 0xdc, 0xab, 0x9c, 0x58, 0x64, 0x0c, 0x76, 0xd9, 0xdd,
	0x35, 0x67, 0x8b, 0xe7, 0xff, 0xff, 0xcf, 0xc7, 0xe6, 0x55, 0xdd, 0x1f, 0x7d, 0xa0, 0xbf, 0xc4,
	0xb4, 0xae, 0x7b, 0x38, 0xfb, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xd8, 0x00, 0x9c, 0x1f, 0x3c, 0x04,
	0x00, 0x00,
}
