// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sqs.proto

package aws

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1da5538be2c44ec, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Message) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Queue struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AccountId            string   `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Queue) Reset()         { *m = Queue{} }
func (m *Queue) String() string { return proto.CompactTextString(m) }
func (*Queue) ProtoMessage()    {}
func (*Queue) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1da5538be2c44ec, []int{1}
}

func (m *Queue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Queue.Unmarshal(m, b)
}
func (m *Queue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Queue.Marshal(b, m, deterministic)
}
func (m *Queue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Queue.Merge(m, src)
}
func (m *Queue) XXX_Size() int {
	return xxx_messageInfo_Queue.Size(m)
}
func (m *Queue) XXX_DiscardUnknown() {
	xxx_messageInfo_Queue.DiscardUnknown(m)
}

var xxx_messageInfo_Queue proto.InternalMessageInfo

func (m *Queue) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Queue) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Queue) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type CreateQueueRequest struct {
	Queue                *Queue       `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	Credentials          *Credentials `protobuf:"bytes,2,opt,name=credentials,proto3" json:"credentials,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateQueueRequest) Reset()         { *m = CreateQueueRequest{} }
func (m *CreateQueueRequest) String() string { return proto.CompactTextString(m) }
func (*CreateQueueRequest) ProtoMessage()    {}
func (*CreateQueueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1da5538be2c44ec, []int{2}
}

func (m *CreateQueueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateQueueRequest.Unmarshal(m, b)
}
func (m *CreateQueueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateQueueRequest.Marshal(b, m, deterministic)
}
func (m *CreateQueueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateQueueRequest.Merge(m, src)
}
func (m *CreateQueueRequest) XXX_Size() int {
	return xxx_messageInfo_CreateQueueRequest.Size(m)
}
func (m *CreateQueueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateQueueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateQueueRequest proto.InternalMessageInfo

func (m *CreateQueueRequest) GetQueue() *Queue {
	if m != nil {
		return m.Queue
	}
	return nil
}

func (m *CreateQueueRequest) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

type CreateQueueResponse struct {
	Queue                *Queue   `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateQueueResponse) Reset()         { *m = CreateQueueResponse{} }
func (m *CreateQueueResponse) String() string { return proto.CompactTextString(m) }
func (*CreateQueueResponse) ProtoMessage()    {}
func (*CreateQueueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1da5538be2c44ec, []int{3}
}

func (m *CreateQueueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateQueueResponse.Unmarshal(m, b)
}
func (m *CreateQueueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateQueueResponse.Marshal(b, m, deterministic)
}
func (m *CreateQueueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateQueueResponse.Merge(m, src)
}
func (m *CreateQueueResponse) XXX_Size() int {
	return xxx_messageInfo_CreateQueueResponse.Size(m)
}
func (m *CreateQueueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateQueueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateQueueResponse proto.InternalMessageInfo

func (m *CreateQueueResponse) GetQueue() *Queue {
	if m != nil {
		return m.Queue
	}
	return nil
}

type SendMessageRequest struct {
	Message              *Message     `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Credentials          *Credentials `protobuf:"bytes,2,opt,name=credentials,proto3" json:"credentials,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SendMessageRequest) Reset()         { *m = SendMessageRequest{} }
func (m *SendMessageRequest) String() string { return proto.CompactTextString(m) }
func (*SendMessageRequest) ProtoMessage()    {}
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1da5538be2c44ec, []int{4}
}

func (m *SendMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageRequest.Unmarshal(m, b)
}
func (m *SendMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageRequest.Marshal(b, m, deterministic)
}
func (m *SendMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageRequest.Merge(m, src)
}
func (m *SendMessageRequest) XXX_Size() int {
	return xxx_messageInfo_SendMessageRequest.Size(m)
}
func (m *SendMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageRequest proto.InternalMessageInfo

func (m *SendMessageRequest) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *SendMessageRequest) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

type SendMessageResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessageResponse) Reset()         { *m = SendMessageResponse{} }
func (m *SendMessageResponse) String() string { return proto.CompactTextString(m) }
func (*SendMessageResponse) ProtoMessage()    {}
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1da5538be2c44ec, []int{5}
}

func (m *SendMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageResponse.Unmarshal(m, b)
}
func (m *SendMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageResponse.Marshal(b, m, deterministic)
}
func (m *SendMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageResponse.Merge(m, src)
}
func (m *SendMessageResponse) XXX_Size() int {
	return xxx_messageInfo_SendMessageResponse.Size(m)
}
func (m *SendMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageResponse proto.InternalMessageInfo

func (m *SendMessageResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ReceiveMessageRequest struct {
	Queue                *Queue       `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	Credentials          *Credentials `protobuf:"bytes,2,opt,name=credentials,proto3" json:"credentials,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReceiveMessageRequest) Reset()         { *m = ReceiveMessageRequest{} }
func (m *ReceiveMessageRequest) String() string { return proto.CompactTextString(m) }
func (*ReceiveMessageRequest) ProtoMessage()    {}
func (*ReceiveMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1da5538be2c44ec, []int{6}
}

func (m *ReceiveMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiveMessageRequest.Unmarshal(m, b)
}
func (m *ReceiveMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiveMessageRequest.Marshal(b, m, deterministic)
}
func (m *ReceiveMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiveMessageRequest.Merge(m, src)
}
func (m *ReceiveMessageRequest) XXX_Size() int {
	return xxx_messageInfo_ReceiveMessageRequest.Size(m)
}
func (m *ReceiveMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiveMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiveMessageRequest proto.InternalMessageInfo

func (m *ReceiveMessageRequest) GetQueue() *Queue {
	if m != nil {
		return m.Queue
	}
	return nil
}

func (m *ReceiveMessageRequest) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

type ReceiveMessageResponse struct {
	Message              *Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiveMessageResponse) Reset()         { *m = ReceiveMessageResponse{} }
func (m *ReceiveMessageResponse) String() string { return proto.CompactTextString(m) }
func (*ReceiveMessageResponse) ProtoMessage()    {}
func (*ReceiveMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1da5538be2c44ec, []int{7}
}

func (m *ReceiveMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiveMessageResponse.Unmarshal(m, b)
}
func (m *ReceiveMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiveMessageResponse.Marshal(b, m, deterministic)
}
func (m *ReceiveMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiveMessageResponse.Merge(m, src)
}
func (m *ReceiveMessageResponse) XXX_Size() int {
	return xxx_messageInfo_ReceiveMessageResponse.Size(m)
}
func (m *ReceiveMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiveMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiveMessageResponse proto.InternalMessageInfo

func (m *ReceiveMessageResponse) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "sqs.Message")
	proto.RegisterType((*Queue)(nil), "sqs.Queue")
	proto.RegisterType((*CreateQueueRequest)(nil), "sqs.CreateQueueRequest")
	proto.RegisterType((*CreateQueueResponse)(nil), "sqs.CreateQueueResponse")
	proto.RegisterType((*SendMessageRequest)(nil), "sqs.SendMessageRequest")
	proto.RegisterType((*SendMessageResponse)(nil), "sqs.SendMessageResponse")
	proto.RegisterType((*ReceiveMessageRequest)(nil), "sqs.ReceiveMessageRequest")
	proto.RegisterType((*ReceiveMessageResponse)(nil), "sqs.ReceiveMessageResponse")
}

func init() {
	proto.RegisterFile("sqs.proto", fileDescriptor_b1da5538be2c44ec)
}

var fileDescriptor_b1da5538be2c44ec = []byte{
	// 352 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0x41, 0x4f, 0xb3, 0x40,
	0x10, 0x2d, 0xed, 0xd7, 0xf6, 0x63, 0x30, 0x8d, 0x99, 0x46, 0x25, 0x18, 0x93, 0x66, 0x0f, 0xc6,
	0x13, 0x35, 0xf4, 0xe0, 0xc1, 0x8b, 0x69, 0x4f, 0x35, 0xe9, 0xa1, 0x70, 0xf3, 0x62, 0x56, 0x98,
	0x18, 0x8c, 0x40, 0x61, 0xa1, 0xfe, 0x60, 0xff, 0x88, 0x61, 0x81, 0x14, 0x0a, 0x89, 0xc6, 0xc4,
	0x1b, 0x33, 0x6f, 0xe6, 0xbd, 0x99, 0x37, 0x2c, 0xa8, 0x22, 0x16, 0xe6, 0x2e, 0x89, 0xd2, 0x08,
	0x07, 0x22, 0x16, 0x86, 0xea, 0xf3, 0xa0, 0x88, 0xd9, 0x02, 0xc6, 0x1b, 0x12, 0x82, 0xbf, 0x12,
	0x4e, 0xa0, 0xbf, 0xf6, 0x74, 0x65, 0xa6, 0xdc, 0xa8, 0x76, 0x7f, 0xed, 0xa1, 0x0e, 0xe3, 0xa0,
	0x80, 0xf4, 0xbe, 0x4c, 0x56, 0x21, 0x7b, 0x84, 0xe1, 0x36, 0xa3, 0xac, 0xdd, 0x82, 0xf0, 0x2f,
	0xe4, 0x41, 0x55, 0x2f, 0xbf, 0xf1, 0x0a, 0x80, 0xbb, 0x6e, 0x94, 0x85, 0xe9, 0xb3, 0xef, 0xe9,
	0x03, 0x89, 0xa8, 0x65, 0x66, 0xed, 0xb1, 0x37, 0xc0, 0x55, 0x42, 0x3c, 0x25, 0xc9, 0x68, 0x53,
	0x9c, 0x91, 0x48, 0x71, 0x06, 0xc3, 0x38, 0x8f, 0x25, 0xb7, 0x66, 0x81, 0x99, 0x6f, 0x50, 0x54,
	0x14, 0x00, 0x5a, 0xa0, 0xb9, 0x09, 0x79, 0x14, 0xa6, 0x3e, 0x7f, 0x17, 0x52, 0x51, 0xb3, 0x4e,
	0xcd, 0x7c, 0xb3, 0xd5, 0x21, 0x6f, 0xd7, 0x8b, 0xd8, 0x1d, 0x4c, 0x1b, 0x5a, 0x62, 0x17, 0x85,
	0x82, 0xbe, 0x17, 0x63, 0x3b, 0x40, 0x87, 0x42, 0xaf, 0x74, 0xaa, 0x1a, 0xf2, 0xfa, 0x60, 0x50,
	0xd1, 0x79, 0x22, 0x3b, 0xab, 0xaa, 0x0a, 0xfc, 0xd5, 0xa8, 0x73, 0x98, 0x36, 0x14, 0xcb, 0x51,
	0xf5, 0xa6, 0x64, 0xed, 0x26, 0x01, 0x9c, 0xd9, 0xe4, 0x92, 0xbf, 0xa7, 0xa3, 0x29, 0xff, 0xc6,
	0xca, 0x07, 0x38, 0x3f, 0x96, 0x2b, 0x47, 0xfc, 0xa1, 0x2b, 0xd6, 0xa7, 0x02, 0xe0, 0x6c, 0x1d,
	0x87, 0x92, 0xbd, 0xef, 0x12, 0x2e, 0x41, 0xab, 0xdd, 0x06, 0x2f, 0x64, 0x53, 0xfb, 0xcf, 0x30,
	0xf4, 0x36, 0x50, 0x08, 0xb3, 0x5e, 0xce, 0x51, 0x33, 0xad, 0xe4, 0x68, 0x1f, 0xae, 0xe4, 0xe8,
	0xf0, 0x97, 0xf5, 0x70, 0x03, 0x93, 0xe6, 0x62, 0x68, 0xc8, 0xea, 0x4e, 0x73, 0x8d, 0xcb, 0x4e,
	0xac, 0x22, 0xbb, 0x55, 0x96, 0xff, 0x9f, 0x46, 0xe6, 0xfc, 0x9e, 0x7f, 0x88, 0x97, 0x91, 0x7c,
	0x70, 0x8b, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x97, 0x89, 0xa0, 0x40, 0x8d, 0x03, 0x00, 0x00,
}
