// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sqs.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1da5538be2c44ec, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Message) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Queue struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AccountId            string   `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Queue) Reset()         { *m = Queue{} }
func (m *Queue) String() string { return proto.CompactTextString(m) }
func (*Queue) ProtoMessage()    {}
func (*Queue) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1da5538be2c44ec, []int{1}
}

func (m *Queue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Queue.Unmarshal(m, b)
}
func (m *Queue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Queue.Marshal(b, m, deterministic)
}
func (m *Queue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Queue.Merge(m, src)
}
func (m *Queue) XXX_Size() int {
	return xxx_messageInfo_Queue.Size(m)
}
func (m *Queue) XXX_DiscardUnknown() {
	xxx_messageInfo_Queue.DiscardUnknown(m)
}

var xxx_messageInfo_Queue proto.InternalMessageInfo

func (m *Queue) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Queue) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Queue) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type CreateQueueRequest struct {
	Queue                *Queue       `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	Credentials          *Credentials `protobuf:"bytes,2,opt,name=credentials,proto3" json:"credentials,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateQueueRequest) Reset()         { *m = CreateQueueRequest{} }
func (m *CreateQueueRequest) String() string { return proto.CompactTextString(m) }
func (*CreateQueueRequest) ProtoMessage()    {}
func (*CreateQueueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1da5538be2c44ec, []int{2}
}

func (m *CreateQueueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateQueueRequest.Unmarshal(m, b)
}
func (m *CreateQueueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateQueueRequest.Marshal(b, m, deterministic)
}
func (m *CreateQueueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateQueueRequest.Merge(m, src)
}
func (m *CreateQueueRequest) XXX_Size() int {
	return xxx_messageInfo_CreateQueueRequest.Size(m)
}
func (m *CreateQueueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateQueueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateQueueRequest proto.InternalMessageInfo

func (m *CreateQueueRequest) GetQueue() *Queue {
	if m != nil {
		return m.Queue
	}
	return nil
}

func (m *CreateQueueRequest) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

type CreateQueueResponse struct {
	Queue                *Queue   `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateQueueResponse) Reset()         { *m = CreateQueueResponse{} }
func (m *CreateQueueResponse) String() string { return proto.CompactTextString(m) }
func (*CreateQueueResponse) ProtoMessage()    {}
func (*CreateQueueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1da5538be2c44ec, []int{3}
}

func (m *CreateQueueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateQueueResponse.Unmarshal(m, b)
}
func (m *CreateQueueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateQueueResponse.Marshal(b, m, deterministic)
}
func (m *CreateQueueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateQueueResponse.Merge(m, src)
}
func (m *CreateQueueResponse) XXX_Size() int {
	return xxx_messageInfo_CreateQueueResponse.Size(m)
}
func (m *CreateQueueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateQueueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateQueueResponse proto.InternalMessageInfo

func (m *CreateQueueResponse) GetQueue() *Queue {
	if m != nil {
		return m.Queue
	}
	return nil
}

type SendMessageRequest struct {
	Message              *Message     `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Credentials          *Credentials `protobuf:"bytes,2,opt,name=credentials,proto3" json:"credentials,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SendMessageRequest) Reset()         { *m = SendMessageRequest{} }
func (m *SendMessageRequest) String() string { return proto.CompactTextString(m) }
func (*SendMessageRequest) ProtoMessage()    {}
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1da5538be2c44ec, []int{4}
}

func (m *SendMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageRequest.Unmarshal(m, b)
}
func (m *SendMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageRequest.Marshal(b, m, deterministic)
}
func (m *SendMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageRequest.Merge(m, src)
}
func (m *SendMessageRequest) XXX_Size() int {
	return xxx_messageInfo_SendMessageRequest.Size(m)
}
func (m *SendMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageRequest proto.InternalMessageInfo

func (m *SendMessageRequest) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *SendMessageRequest) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

type SendMessageResponse struct {
	Response             *BaseResponse `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SendMessageResponse) Reset()         { *m = SendMessageResponse{} }
func (m *SendMessageResponse) String() string { return proto.CompactTextString(m) }
func (*SendMessageResponse) ProtoMessage()    {}
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1da5538be2c44ec, []int{5}
}

func (m *SendMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageResponse.Unmarshal(m, b)
}
func (m *SendMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageResponse.Marshal(b, m, deterministic)
}
func (m *SendMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageResponse.Merge(m, src)
}
func (m *SendMessageResponse) XXX_Size() int {
	return xxx_messageInfo_SendMessageResponse.Size(m)
}
func (m *SendMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageResponse proto.InternalMessageInfo

func (m *SendMessageResponse) GetResponse() *BaseResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

type ReceiveMessageRequest struct {
	Queue                *Queue       `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	Credentials          *Credentials `protobuf:"bytes,2,opt,name=credentials,proto3" json:"credentials,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReceiveMessageRequest) Reset()         { *m = ReceiveMessageRequest{} }
func (m *ReceiveMessageRequest) String() string { return proto.CompactTextString(m) }
func (*ReceiveMessageRequest) ProtoMessage()    {}
func (*ReceiveMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1da5538be2c44ec, []int{6}
}

func (m *ReceiveMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiveMessageRequest.Unmarshal(m, b)
}
func (m *ReceiveMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiveMessageRequest.Marshal(b, m, deterministic)
}
func (m *ReceiveMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiveMessageRequest.Merge(m, src)
}
func (m *ReceiveMessageRequest) XXX_Size() int {
	return xxx_messageInfo_ReceiveMessageRequest.Size(m)
}
func (m *ReceiveMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiveMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiveMessageRequest proto.InternalMessageInfo

func (m *ReceiveMessageRequest) GetQueue() *Queue {
	if m != nil {
		return m.Queue
	}
	return nil
}

func (m *ReceiveMessageRequest) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

type ReceiveMessageResponse struct {
	Message              *Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiveMessageResponse) Reset()         { *m = ReceiveMessageResponse{} }
func (m *ReceiveMessageResponse) String() string { return proto.CompactTextString(m) }
func (*ReceiveMessageResponse) ProtoMessage()    {}
func (*ReceiveMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1da5538be2c44ec, []int{7}
}

func (m *ReceiveMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiveMessageResponse.Unmarshal(m, b)
}
func (m *ReceiveMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiveMessageResponse.Marshal(b, m, deterministic)
}
func (m *ReceiveMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiveMessageResponse.Merge(m, src)
}
func (m *ReceiveMessageResponse) XXX_Size() int {
	return xxx_messageInfo_ReceiveMessageResponse.Size(m)
}
func (m *ReceiveMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiveMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiveMessageResponse proto.InternalMessageInfo

func (m *ReceiveMessageResponse) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "sqs.Message")
	proto.RegisterType((*Queue)(nil), "sqs.Queue")
	proto.RegisterType((*CreateQueueRequest)(nil), "sqs.CreateQueueRequest")
	proto.RegisterType((*CreateQueueResponse)(nil), "sqs.CreateQueueResponse")
	proto.RegisterType((*SendMessageRequest)(nil), "sqs.SendMessageRequest")
	proto.RegisterType((*SendMessageResponse)(nil), "sqs.SendMessageResponse")
	proto.RegisterType((*ReceiveMessageRequest)(nil), "sqs.ReceiveMessageRequest")
	proto.RegisterType((*ReceiveMessageResponse)(nil), "sqs.ReceiveMessageResponse")
}

func init() {
	proto.RegisterFile("sqs.proto", fileDescriptor_b1da5538be2c44ec)
}

var fileDescriptor_b1da5538be2c44ec = []byte{
	// 367 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0x4d, 0x4f, 0x83, 0x40,
	0x10, 0x2d, 0xad, 0xb5, 0x32, 0x98, 0x6a, 0xa6, 0xd1, 0x12, 0x8c, 0x49, 0xc3, 0xc1, 0x78, 0x22,
	0x86, 0x1e, 0x3c, 0x78, 0x31, 0xed, 0xa9, 0x4d, 0x7a, 0x28, 0xdc, 0xbc, 0x98, 0x15, 0x26, 0x06,
	0x23, 0x50, 0x58, 0xe8, 0x1f, 0xf6, 0x8f, 0x18, 0x96, 0xdd, 0x7e, 0xd1, 0x44, 0x63, 0xe2, 0x09,
	0x76, 0xdf, 0x9b, 0xf7, 0x66, 0xde, 0x00, 0xe8, 0x3c, 0xe3, 0xce, 0x2a, 0x4f, 0x8b, 0x14, 0x3b,
	0x3c, 0xe3, 0x96, 0x1e, 0xb1, 0xb8, 0x3e, 0x5b, 0x17, 0x39, 0xf1, 0x55, 0x9a, 0x70, 0x92, 0x04,
	0x7b, 0x0c, 0xbd, 0x05, 0x71, 0xce, 0xde, 0x09, 0xfb, 0xd0, 0x9e, 0x85, 0xa6, 0x36, 0xd2, 0xee,
	0x75, 0xaf, 0x3d, 0x0b, 0xd1, 0x84, 0x5e, 0x5c, 0x43, 0x66, 0x5b, 0x5c, 0xaa, 0xa3, 0x3d, 0x87,
	0xee, 0xb2, 0xa4, 0xb2, 0x59, 0x82, 0x70, 0x92, 0xb0, 0x58, 0xf1, 0xc5, 0x3b, 0xde, 0x02, 0xb0,
	0x20, 0x48, 0xcb, 0xa4, 0x78, 0x8d, 0x42, 0xb3, 0x23, 0x10, 0x5d, 0xde, 0xcc, 0x42, 0xfb, 0x03,
	0x70, 0x9a, 0x13, 0x2b, 0x48, 0x28, 0x7a, 0x94, 0x95, 0xc4, 0x0b, 0x1c, 0x41, 0x37, 0xab, 0xce,
	0x42, 0xdb, 0x70, 0xc1, 0xa9, 0x46, 0xaa, 0x19, 0x35, 0x80, 0x2e, 0x18, 0x41, 0x4e, 0x21, 0x25,
	0x45, 0xc4, 0x3e, 0xb9, 0x70, 0x34, 0xdc, 0x4b, 0xa7, 0x1a, 0x75, 0xba, 0xbd, 0xf7, 0x76, 0x49,
	0xf6, 0x23, 0x0c, 0xf6, 0xbc, 0xea, 0x28, 0x7e, 0x36, 0xb3, 0x57, 0x80, 0x3e, 0x25, 0xa1, 0x4c,
	0x4a, 0x35, 0x79, 0xb7, 0x0d, 0xa8, 0xae, 0x3c, 0x17, 0x95, 0x8a, 0xa5, 0xc0, 0x3f, 0xb5, 0x3a,
	0x87, 0xc1, 0x9e, 0xa3, 0x6c, 0x75, 0x0c, 0x67, 0x6a, 0x83, 0xd2, 0x73, 0xe8, 0x6c, 0x57, 0x3a,
	0x61, 0x7c, 0x43, 0xf5, 0x36, 0x44, 0x3b, 0x86, 0x2b, 0x8f, 0x02, 0x8a, 0xd6, 0x74, 0x30, 0xc0,
	0xff, 0xa4, 0xfc, 0x0c, 0xd7, 0x87, 0x76, 0xb2, 0xfb, 0x5f, 0x06, 0xe6, 0x7e, 0x69, 0x00, 0xfe,
	0xd2, 0xf7, 0x29, 0x5f, 0x47, 0x01, 0xe1, 0x04, 0x8c, 0x9d, 0xb5, 0xe1, 0x50, 0x14, 0x35, 0x3f,
	0x1a, 0xcb, 0x6c, 0x02, 0x32, 0x81, 0x56, 0xa5, 0xb1, 0x93, 0xa7, 0xd4, 0x68, 0xee, 0x54, 0x6a,
	0x1c, 0x89, 0xde, 0x6e, 0xe1, 0x02, 0xfa, 0xfb, 0x83, 0xa1, 0x25, 0xd8, 0x47, 0xc3, 0xb5, 0x6e,
	0x8e, 0x62, 0x4a, 0xec, 0x41, 0x9b, 0xe8, 0x2f, 0x3d, 0xe7, 0x49, 0xfc, 0x85, 0x6f, 0xa7, 0xe2,
	0x31, 0xfe, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x1c, 0x6d, 0x5d, 0x44, 0xba, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SQSServiceClient is the client API for SQSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SQSServiceClient interface {
	CreateQueue(ctx context.Context, in *CreateQueueRequest, opts ...grpc.CallOption) (*CreateQueueResponse, error)
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
	ReceiveMessage(ctx context.Context, in *ReceiveMessageRequest, opts ...grpc.CallOption) (SQSService_ReceiveMessageClient, error)
}

type sQSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSQSServiceClient(cc grpc.ClientConnInterface) SQSServiceClient {
	return &sQSServiceClient{cc}
}

func (c *sQSServiceClient) CreateQueue(ctx context.Context, in *CreateQueueRequest, opts ...grpc.CallOption) (*CreateQueueResponse, error) {
	out := new(CreateQueueResponse)
	err := c.cc.Invoke(ctx, "/sqs.SQSService/CreateQueue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sQSServiceClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	out := new(SendMessageResponse)
	err := c.cc.Invoke(ctx, "/sqs.SQSService/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sQSServiceClient) ReceiveMessage(ctx context.Context, in *ReceiveMessageRequest, opts ...grpc.CallOption) (SQSService_ReceiveMessageClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SQSService_serviceDesc.Streams[0], "/sqs.SQSService/ReceiveMessage", opts...)
	if err != nil {
		return nil, err
	}
	x := &sQSServiceReceiveMessageClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SQSService_ReceiveMessageClient interface {
	Recv() (*ReceiveMessageResponse, error)
	grpc.ClientStream
}

type sQSServiceReceiveMessageClient struct {
	grpc.ClientStream
}

func (x *sQSServiceReceiveMessageClient) Recv() (*ReceiveMessageResponse, error) {
	m := new(ReceiveMessageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SQSServiceServer is the server API for SQSService service.
type SQSServiceServer interface {
	CreateQueue(context.Context, *CreateQueueRequest) (*CreateQueueResponse, error)
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	ReceiveMessage(*ReceiveMessageRequest, SQSService_ReceiveMessageServer) error
}

// UnimplementedSQSServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSQSServiceServer struct {
}

func (*UnimplementedSQSServiceServer) CreateQueue(ctx context.Context, req *CreateQueueRequest) (*CreateQueueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateQueue not implemented")
}
func (*UnimplementedSQSServiceServer) SendMessage(ctx context.Context, req *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (*UnimplementedSQSServiceServer) ReceiveMessage(req *ReceiveMessageRequest, srv SQSService_ReceiveMessageServer) error {
	return status.Errorf(codes.Unimplemented, "method ReceiveMessage not implemented")
}

func RegisterSQSServiceServer(s *grpc.Server, srv SQSServiceServer) {
	s.RegisterService(&_SQSService_serviceDesc, srv)
}

func _SQSService_CreateQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SQSServiceServer).CreateQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sqs.SQSService/CreateQueue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SQSServiceServer).CreateQueue(ctx, req.(*CreateQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SQSService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SQSServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sqs.SQSService/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SQSServiceServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SQSService_ReceiveMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReceiveMessageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SQSServiceServer).ReceiveMessage(m, &sQSServiceReceiveMessageServer{stream})
}

type SQSService_ReceiveMessageServer interface {
	Send(*ReceiveMessageResponse) error
	grpc.ServerStream
}

type sQSServiceReceiveMessageServer struct {
	grpc.ServerStream
}

func (x *sQSServiceReceiveMessageServer) Send(m *ReceiveMessageResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _SQSService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sqs.SQSService",
	HandlerType: (*SQSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateQueue",
			Handler:    _SQSService_CreateQueue_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _SQSService_SendMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReceiveMessage",
			Handler:       _SQSService_ReceiveMessage_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sqs.proto",
}
